import type { CategoryKey } from "../communityDataConfig";

export const GEO_SEASON_QUERY_PACK: Partial<
  Record<
    CategoryKey,
    Record<string, Record<string, string[]>>
  >
> = {
  nature_outdoors: {
    pacific_northwest: {
      january: ["winter waterfall hike", "rainforest trail walk"],
      february: ["coastal storm lookout", "rainforest boardwalk trail"],
      march: ["spring waterfall hike", "early wildflower trail"],
      april: ["tulip festival", "cherry blossom park"],
      may: ["wildflower ridge trail", "snowmelt waterfall trail"],
      june: ["alpine lake hike", "cedar grove trail"],
      july: ["mountain lake campground", "berry picking trail"],
      august: ["wildflower meadow hike", "alpine ridge hike"],
      september: ["river overlook trail", "early fall forest hike"],
      october: ["fall color hike", "pumpkin patch farm"],
      november: ["coastal viewpoint walk", "storm watching beach"],
      december: ["snowy forest trail", "christmas tree farm"]
    },
    mountain: {
      january: ["ski resort", "winter scenic overlook"],
      february: ["snowy trailhead hike", "hot springs winter soak"],
      march: ["late season skiing", "spring snow hike"],
      april: ["foothills wildflower hike", "snowmelt waterfall trail"],
      may: ["aspen grove spring trail", "mountain pass scenic drive"],
      june: ["high alpine lake hike", "wildflower meadow trail"],
      july: ["mountain reservoir boat rentals", "wildflower trail hike"],
      august: ["high peak summit", "alpine meadow hike"],
      september: ["aspen scenic byway", "mountain pass fall colors"],
      october: ["wildlife viewing area", "late season aspen hike"],
      november: ["early snow hiking trail", "ridge overlook walk"],
      december: ["snowshoe loop trail", "ski village lights"]
    },
    desert_southwest: {
      january: ["saguaro desert hike", "sonoran scenic trail"],
      february: ["sunrise summit trail", "desert butte hike"],
      march: ["desert wildflower bloom", "poppy trail walk"],
      april: ["desert canyon wildflowers", "spring desert ridge hike"],
      may: ["cactus bloom trail", "early morning desert hike"],
      june: ["sunrise desert ridge", "summer solstice overlook"],
      july: ["monsoon desert overlook", "cool cavern tour"],
      august: ["desert after rain trail", "monsoon storm viewpoints"],
      september: ["cooler desert sunrise hike", "canyon trail hike"],
      october: ["red rock canyon trail", "fall desert hike"],
      november: ["desert botanical garden walk", "slot canyon hike"],
      december: ["winter desert sunrise", "desert sunset overlook"]
    },
    gulf_coast: {
      january: ["winter coastal birding", "barrier island beach walk"],
      february: ["bayou tour", "winter bird migration coast"],
      march: ["spring bird migration coast", "swamp boardwalk trail"],
      april: ["spring swamp boat tour", "bird sanctuary walk"],
      may: ["sea turtle nesting beach", "coastal dune wildflowers"],
      june: ["sunrise summer beach", "early morning bayou tour"],
      july: ["coastal wildlife walk", "summer birding refuge"],
      august: ["airboat swamp tour", "bayou boardwalk trail"],
      september: ["shorebird migration", "pleasant evening beach"],
      october: ["fall bird migration", "swamp fall colors"],
      november: ["late fall coastal birding", "migration coast walk"],
      december: ["winter birding refuge", "holiday beach walk"]
    },
    atlantic_south: {
      january: ["winter barrier island walk", "maritime forest trail"],
      february: ["whale watching cruise", "winter coastal nature trail"],
      march: ["spring beach nature walk", "coastal marsh boardwalk"],
      april: ["beach dune wildflowers", "spring maritime forest hike"],
      may: ["sea turtle nesting beach", "memorial day beach sunrise"],
      june: ["turtle nesting walk", "summer solstice beach"],
      july: ["sunrise beach walk", "salt marsh kayak tour"],
      august: ["beach nature preserve", "morning forest trail"],
      september: ["fall coastal bird migration", "pleasant weather beach"],
      october: ["fall barrier island hike", "cool coastal trail"],
      november: ["thanksgiving beach sunrise", "late fall coastal hike"],
      december: ["winter dunes nature walk", "holiday beach stroll"]
    },
    mid_atlantic: {
      january: ["winter bayfront trail", "estuary overlook"],
      february: ["wildlife viewing area", "winter state park shoreline"],
      march: ["spring shorebird migration bay", "early spring marsh trail"],
      april: ["cherry blossom waterfront walk", "spring estuary boardwalk"],
      may: ["memorial day bay trail", "spring coastal rail trail"],
      june: ["summer solstice bayfront", "island nature trail bay"],
      july: ["wild horses beach access", "summer bayfront path"],
      august: ["late summer bay sunset", "coastal wildlife preserve"],
      september: ["fall migration bay overlook", "cool weather bay trail"],
      october: ["fall foliage overlook", "autumn state park loop"],
      november: ["thanksgiving bayfront walk", "late fall coastal colors"],
      december: ["winter coastal boardwalk", "holiday harbor lights"]
    },
    new_england: {
      january: ["winter coastal lighthouse", "snowy harbor walk"],
      february: ["rocky winter coastline", "seaside trail walk"],
      march: ["maple sugar house tour", "early spring coastal walk"],
      april: ["spring lighthouse trail", "maple syrup farm visit"],
      may: ["memorial day coastal walk", "lighthouse seaside trail"],
      june: ["summer solstice beach", "carriage road biking"],
      july: ["carriage road hike", "summer coastal cliff trail"],
      august: ["late summer rocky coast", "lighthouse scenic overlook"],
      september: ["scenic highway foliage drive", "early fall mountain colors"],
      october: ["peak foliage mountain hike", "covered bridge foliage tour"],
      november: ["thanksgiving coastal stroll", "late fall lighthouse visit"],
      december: ["winter harbor village walk", "holiday lighthouse lights"]
    },
    great_lakes: {
      january: ["winter lakeshore walk", "ice formations along lake"],
      february: ["ice caves lakeshore", "winter dune overlook"],
      march: ["early spring lakeshore walk", "spring thaw river trail"],
      april: ["spring dune boardwalk", "riverwalk blossom trail"],
      may: ["memorial day beach park", "spring lakefront bike trail"],
      june: ["summer solstice lakeshore", "bluff lakeshore trail"],
      july: ["dune climb lake overlook", "summer harbor lakefront"],
      august: ["late summer beach day", "great lakes sunset overlook"],
      september: ["fall color lakeshore drive", "autumn riverwalk foliage"],
      october: ["fall dunes overlook", "lakeshore fall color trail"],
      november: ["thanksgiving lakefront walk", "late fall dune trail"],
      december: ["winter lakeshore lights", "holiday riverwalk lights"]
    },
    california: {
      january: ["whale watching overlook", "elephant seal viewing area"],
      february: ["whale watching cruise", "almond blossom scenic drive"],
      march: ["poppy bloom reserve", "wildflower trail"],
      april: ["wildflower overlook", "spring canyon hike"],
      may: ["foothill wildflower trail", "coastal bluff hiking trail"],
      june: ["summer solstice beach walk", "morning fog coastal trail"],
      july: ["coastal morning hike", "redwood grove shaded trail"],
      august: ["cool coastal bluff walk", "redwood canyon trail"],
      september: ["pleasant beach day", "fall canyon hike"],
      october: ["wine country harvest hike", "autumn canyon overlook"],
      november: ["thanksgiving coastal hike", "fall vineyard color walk"],
      december: ["winter whale watching", "holiday coastal harbor walk"]
    },
    hawaii: {
      january: ["whale lookout", "waterfall valley hike"],
      february: ["whale watching cruise", "island nature event"],
      march: ["tropical spring bloom hike", "waterfall scenic drive"],
      april: ["waterfall canyon trail", "tropical garden walk"],
      may: ["memorial day beach park", "tropical flower garden visit"],
      june: ["summer solstice island beach", "tropical garden tour"],
      july: ["reef snorkel spot", "summer beach day"],
      august: ["white sand beach day", "tropical garden peak bloom"],
      september: ["pleasant ridge hike", "tropical forest trail"],
      october: ["beach sunset walk", "comfortable trail hike"],
      november: ["whale season lookout", "tropical arboretum walk"],
      december: ["whale season lookout", "holiday beach lights"]
    },
    alaska: {
      january: ["winter scenic overlook", "hot springs visit"],
      february: ["winter night sky tour", "cozy winter cabin stay"],
      march: ["late winter tour", "sled dog trail"],
      april: ["spring wildlife viewing drive", "glacier boat tour"],
      may: ["midnight sun hiking trail", "spring wilderness day hike"],
      june: ["midnight sun festival park", "summer solstice hike"],
      july: ["salmon viewing platform", "bear viewing river"],
      august: ["salmon run waterfall", "wildlife viewing area"],
      september: ["fall colors national park", "early fall scenic drive"],
      october: ["fall scenic overlook", "autumn trail walk"],
      november: ["winter tour meeting point", "cozy cabin overlook"],
      december: ["holiday winter tour", "winter lodge lights"]
    }
  },
  
  sports_rec: {
    pacific_northwest: {
      january: ["indoor climbing gym", "ski resort slopes"],
      february: ["snowboarding terrain park", "local ski hill"],
      march: ["spring skiing", "early season mountain biking"],
      april: ["sea kayak tour", "spring trail mountain biking"],
      may: ["sea kayaking tour", "mountain bike flow trails"],
      june: ["paddleboard or kayak rental", "alpine mountain bike trail"],
      july: ["whitewater rafting", "downhill bike park"],
      august: ["late summer sea kayaking", "forest trail running"],
      september: ["fall mountain bike loop", "autumn kayak tours"],
      october: ["fall foliage bike trail", "indoor climbing gym"],
      november: ["early ski season", "bouldering gym"],
      december: ["ski resort opening", "winter sports pass"]
    },
    mountain: {
      january: ["alpine ski resort", "ski slopes"],
      february: ["powder day ski area", "snowboarding terrain park"],
      march: ["spring skiing", "late season ski days"],
      april: ["mountain bike trail opening", "fly fishing river"],
      may: ["singletrack mountain biking", "valley fly fishing"],
      june: ["lift-served bike park", "high alpine mountain biking"],
      july: ["downhill bike park", "summer mountain adventure park"],
      august: ["late summer singletrack", "high elevation trail running"],
      september: ["fall colors mountain biking", "trail running ridge views"],
      october: ["shoulder-season biking", "autumn fly fishing"],
      november: ["ice climbing park", "early season ski laps"],
      december: ["ski resort opening", "snowboard park season"]
    },
    desert_southwest: {
      january: ["winter desert golf", "rock climbing area"],
      february: ["spring training baseball", "desert climbing area"],
      march: ["prime desert mountain biking", "rock climbing season"],
      april: ["morning climbing", "desert preserve singletrack"],
      may: ["sunrise desert golf round", "early morning climbing"],
      june: ["desert lake boating", "indoor climbing gym"],
      july: ["sunrise golf tee time", "water park day"],
      august: ["early morning outdoor sports", "indoor rock climbing gym"],
      september: ["desert mountain biking returns", "pleasant weather climbing"],
      october: ["perfect desert golf weather", "climbing preserve"],
      november: ["fall desert golf", "prime climbing season"],
      december: ["winter desert golf escape", "holiday climbing trip"]
    },
    gulf_coast: {
      january: ["winter coastal golf", "fishing charter"],
      february: ["inshore fishing charter", "bayou kayak tour"],
      march: ["spring coastal golf", "bayou kayak season"],
      april: ["local fishing charter", "guided kayak tour"],
      may: ["memorial day fishing trip", "guided kayak tours"],
      june: ["early morning fishing charter", "sunrise bayou paddle"],
      july: ["sunrise fishing charter", "dawn kayak eco tour"],
      august: ["early morning inshore fishing", "summer kayak tours"],
      september: ["inshore fishing season", "pleasant evening kayaking"],
      october: ["fall fishing peak", "autumn bayou kayak"],
      november: ["thanksgiving fishing trip", "late season kayak tour"],
      december: ["winter fishing charter", "holiday coastal golf"]
    },
    atlantic_south: {
      january: ["winter island golf", "ocean fishing pier"],
      february: ["resort island golf", "winter pier fishing"],
      march: ["spring coastal golf", "early season surfing"],
      april: ["surf break", "beach volleyball pickup"],
      may: ["memorial day beach sports", "early summer surf"],
      june: ["summer surf sessions", "beach volleyball tournament"],
      july: ["peak summer surfing", "beach paddle sports"],
      august: ["late summer surf", "evening beach volleyball"],
      september: ["fall surf swells", "shoulder-season golf"],
      october: ["fall surf season", "cool weather golf"],
      november: ["thanksgiving golf round", "fall inshore fishing"],
      december: ["winter coastal golf", "holiday pier fishing"]
    },
    mid_atlantic: {
      january: ["indoor sports complex", "ice skating rink"],
      february: ["downtown ice rink", "indoor climbing wall"],
      march: ["early spring golf range", "sailing club opening"],
      april: ["bay sailing lessons", "harbor kayak rental opens"],
      may: ["memorial day bay sailing", "harbor kayak tours"],
      june: ["summer sunset sail", "peak season kayak rentals"],
      july: ["bay sailing charter", "kayak harbor paddle"],
      august: ["late summer sunset sail", "guided kayak tour"],
      september: ["fall harbor sailing", "autumn bay kayaking"],
      october: ["crisp weather sailing", "fall foliage kayak"],
      november: ["thanksgiving golf special", "late season sailing"],
      december: ["winter ice skating rink", "holiday indoor sports"]
    },
    new_england: {
      january: ["northeastern ski resort", "outdoor ice skating"],
      february: ["alpine skiing weekend", "community ice rink"],
      march: ["late season spring skiing", "spring sailing prep day"],
      april: ["harbor sailing season opens", "whale watching tour"],
      may: ["memorial day harbor sail", "early season whale watching"],
      june: ["summer sunset sail", "whale watching peak season"],
      july: ["harbor daysail charter", "whale watching excursion"],
      august: ["late summer coastal sailing", "whale watching trip"],
      september: ["fall foliage sailing", "shoulder-season whale tour"],
      october: ["coastal fall sailing", "autumn lighthouse boat tour"],
      november: ["late season harbor sail", "early ski season opening"],
      december: ["holiday ski getaway", "frozen pond ice skating"]
    },
    great_lakes: {
      january: ["ice fishing spot", "lakeside ice skating rink"],
      february: ["ice fishing season", "downtown outdoor rink"],
      march: ["late ice fishing season", "spring sports league signup"],
      april: ["open water fishing opener", "marina boat rental"],
      may: ["memorial day fishing trip", "start of boat rental season"],
      june: ["summer lake fishing", "river boat sightseeing"],
      july: ["lake fishing charter", "pontoon boat rental"],
      august: ["late summer fishing", "harbor boat tours"],
      september: ["fall fishing run", "shoulder-season boat rental"],
      october: ["fall river fishing", "autumn color boat tour"],
      november: ["ice fishing gear prep", "late season shoreline fishing"],
      december: ["holiday ice fishing trip", "lakeside ice skating park"]
    },
    california: {
      january: ["winter surf break", "coastal golf course"],
      february: ["winter swell surfing", "dry-season mountain biking"],
      march: ["spring beach surfing", "trail mountain biking opener"],
      april: ["spring beach pickup games", "singletrack mountain biking"],
      may: ["memorial day surf weekend", "early summer trail riding"],
      june: ["summer surf session", "lakeside bike loop"],
      july: ["beach break surfing", "alpine mountain biking"],
      august: ["late summer surf", "peak season trail riding"],
      september: ["fall surf season", "cooler mountain biking"],
      october: ["surf days", "fall color bike trails"],
      november: ["thanksgiving surf trip", "shoulder-season biking"],
      december: ["winter swell surf", "holiday coastal bike ride"]
    },
    hawaii: {
      january: ["winter north shore surf", "reef snorkeling bay"],
      february: ["big wave surf event", "guided snorkel tour"],
      march: ["spring surf sessions", "snorkeling crater reef"],
      april: ["calm water snorkeling", "beginner surf lessons"],
      may: ["memorial day surf weekend", "snorkeling clear water"],
      june: ["summer surf", "boat snorkel tours"],
      july: ["night snorkel tour", "daytime reef snorkel"],
      august: ["late summer surf", "ideal snorkeling conditions"],
      september: ["shoulder-season surf", "snorkeling shoulder season"],
      october: ["fall surf conditions", "guided snorkel tour"],
      november: ["winter surf season", "snorkel tour outing"],
      december: ["winter surf event", "holiday snorkel tour"]
    },
    alaska: {
      january: ["dog sledding tour", "winter snowshoe tour"],
      february: ["sled race tour", "winter adventure sports"],
      march: ["sled dog checkpoint visit", "spring dog mushing tour"],
      april: ["spring fishing season", "early season wildlife boat"],
      may: ["memorial day river fishing", "kayak season kickoff"],
      june: ["midnight sun river fishing", "fjord sea kayaking"],
      july: ["salmon sport fishing", "peak season sea kayaking"],
      august: ["late salmon run fishing", "glacier kayak tour"],
      september: ["fall fishing", "fall coastal kayaking"],
      october: ["late fall river fishing", "aurora tour"],
      november: ["dog mushing season opens", "early winter tour"],
      december: ["holiday dog sled ride", "winter tour"]
    }
  },

  attractions: {
    pacific_northwest: {
      january: ["public market", "art museum"],
      february: ["food and wine festival", "chocolate tour"],
      march: ["spring market", "farmers market"],
      april: ["tulip festival", "brewery tour"],
      may: ["farmers market", "brewery tour"],
      june: ["summer market", "open-air market"],
      july: ["summer festival", "street market"],
      august: ["summer festival", "sand sculpture festival"],
      september: ["harvest festival", "fall brewery tour"],
      october: ["oktoberfest celebration", "fall festival"],
      november: ["holiday market preview", "seafood festival"],
      december: ["holiday market", "holiday lights display"]
    },
    mountain: {
      january: ["mountain hot springs", "scenic winter railway"],
      february: ["hot springs soak", "resort spa"],
      march: ["hot springs visit", "national park visitor center"],
      april: ["heritage train ride", "spring mountain resort"],
      may: ["scenic mountain railroad", "alpine hot springs"],
      june: ["mountain games festival", "summer scenic railway"],
      july: ["mountain music festival", "hot springs evening soak"],
      august: ["scenic train ride", "mountain hot springs"],
      september: ["fall foliage train", "hot springs fall visit"],
      october: ["fall foliage train ride", "mountain hot springs"],
      november: ["scenic railway", "cozy hot springs getaway"],
      december: ["holiday train ride", "winter hot springs visit"]
    },
    desert_southwest: {
      january: ["natural history museum", "cultural museum"],
      february: ["botanical garden", "heritage museum"],
      march: ["spring botanical garden", "historic mission site"],
      april: ["botanical garden bloom walk", "caverns tour"],
      may: ["morning museum visit", "heritage site tour"],
      june: ["architectural walking tour", "indoor museum"],
      july: ["caverns tour", "history museum"],
      august: ["museum visit", "historic site"],
      september: ["fall botanical garden", "heritage walking tours"],
      october: ["botanical garden evening", "fall procession event"],
      november: ["heritage museum", "historic district tour"],
      december: ["holiday garden walk", "holiday lights event"]
    },
    gulf_coast: {
      january: ["aquarium visit", "historic district walk"],
      february: ["parade route", "historic district tour"],
      march: ["spring parade", "plantation tour"],
      april: ["spring festival", "aquarium visit"],
      may: ["zoo visit", "aquarium peak season"],
      june: ["summer aquarium visit", "historic house tour"],
      july: ["aquarium visit", "historic walking tour"],
      august: ["aquarium visit", "historic district tour"],
      september: ["fall aquarium visit", "heritage festival"],
      october: ["zoo event", "historic ghost tour"],
      november: ["heritage event", "historic district stroll"],
      december: ["holiday lights festival", "holiday riverfront events"]
    },
    atlantic_south: {
      january: ["lighthouse overlook", "ocean aquarium"],
      february: ["lighthouse tour", "fishing pier walk"],
      march: ["spring lighthouse visit", "pier season opening"],
      april: ["lighthouse tour", "pier activities"],
      may: ["memorial day lighthouse visit", "pier rides and games"],
      june: ["summer lighthouse tours", "pier attractions"],
      july: ["lighthouse tour", "pier summer festival"],
      august: ["late summer lighthouse stop", "pier summer activities"],
      september: ["fall lighthouse visit", "fall pier events"],
      october: ["lighthouse tour", "fall pier festival"],
      november: ["lighthouse visit", "quiet pier walk"],
      december: ["holiday lighthouse lights", "holiday pier light display"]
    },
    mid_atlantic: {
      january: ["museums visit", "maritime museum"],
      february: ["museum weekend", "history museum"],
      march: ["cherry blossom preview walk", "spring maritime museum"],
      april: ["cherry blossom festival", "tidal basin walk"],
      may: ["monuments tour", "boardwalk season opening"],
      june: ["summer boardwalk", "museum visit"],
      july: ["national mall visit", "boardwalk peak season"],
      august: ["late summer boardwalk night", "museum visit"],
      september: ["fall museum visits", "fall boardwalk stroll"],
      october: ["museum weekend", "harvest-themed boardwalk"],
      november: ["museum weekend", "late fall maritime museum"],
      december: ["holiday tree display", "holiday maritime display"]
    },
    new_england: {
      january: ["winter lighthouse visit", "maritime museum"],
      february: ["lighthouse winter visit", "local history museum"],
      march: ["maple sugar house tour", "spring lighthouse visit"],
      april: ["lighthouse spring tour", "harbor cruise season opens"],
      may: ["memorial day lighthouse visit", "harbor sightseeing tours"],
      june: ["summer lighthouse tour", "historic harbor walk"],
      july: ["lighthouse summer festival", "harbor tour peak season"],
      august: ["late summer lighthouse stop", "harbor tours"],
      september: ["fall lighthouse visit", "harbor foliage tours"],
      october: ["fall festival", "lighthouse tour"],
      november: ["maritime museum visit", "late fall lighthouse stop"],
      december: ["holiday lighthouse lights", "holiday island stroll"]
    },
    great_lakes: {
      january: ["winter lakefront walk", "natural history museum"],
      february: ["science museum visit", "city museum"],
      march: ["art museum day", "early spring lakefront walk"],
      april: ["spring lakefront walk", "brewery tour season opening"],
      may: ["memorial day lakefront visit", "brewery tour season"],
      june: ["summer lakefront", "summer brewery tour"],
      july: ["summer fireworks show", "brewery summer festival"],
      august: ["late summer lakefront evening", "brewery tour weekend"],
      september: ["fall brewery tour", "fall lakefront stroll"],
      october: ["oktoberfest brewery event", "crisp fall lakefront"],
      november: ["brewery visit", "late fall lakefront walk"],
      december: ["holiday market", "holiday brewery event"]
    },
    california: {
      january: ["coastal aquarium", "coastal wildlife viewing"],
      february: ["whale watch cruise", "almond blossom scenic tour"],
      march: ["spring winery tasting", "whale watching season"],
      april: ["barrel tasting weekend", "spring winery tour"],
      may: ["winery tour season", "mission trail walking tour"],
      june: ["summer winery picnic", "aquarium visit"],
      july: ["summer convention", "winery evening event"],
      august: ["late summer winery visit", "theme park day"],
      september: ["wine crush season", "harvest festival"],
      october: ["pumpkin harvest festival", "fall winery harvest tour"],
      november: ["winery visit", "fall harvest tasting tour"],
      december: ["holiday winery lights", "holiday theme park visit"]
    },
    hawaii: {
      january: ["whale watching tour", "luau cultural show"],
      february: ["whale festival", "whale watching season"],
      march: ["island cultural festival", "volcano sightseeing tour"],
      april: ["hula festival", "spring luau evening"],
      may: ["lei day celebration", "volcano guided tours"],
      june: ["cultural parade", "island cultural center"],
      july: ["summer luau show", "volcano summit tours"],
      august: ["bon dance festival", "volcano park visit"],
      september: ["aloha festival events", "island cultural center visit"],
      october: ["food and wine festival", "fall volcano excursion"],
      november: ["holiday luau dinner", "cultural center exhibits"],
      december: ["holiday luau show", "holiday cultural celebration"]
    },
    alaska: {
      january: ["winter scenic tour", "wildlife center visit"],
      february: ["winter festival", "wildlife viewing"],
      march: ["sled race event", "spring tour"],
      april: ["wildlife center visit", "glacier cruise preview"],
      may: ["glacier cruise", "wildlife center walk"],
      june: ["midnight sun festival", "glacier cruise season"],
      july: ["summer glacier cruise", "salmon hatchery tour"],
      august: ["bear viewing platform", "wildlife viewing tour"],
      september: ["fall glacier cruise", "early fall scenic tour"],
      october: ["fall tour", "wildlife excursions"],
      november: ["winter tour season", "heritage cultural center"],
      december: ["holiday festival", "winter scenic tour"]
    }
  },

  community_events: {
    pacific_northwest: {
      january: ["new year celebration", "winter lights festival"],
      february: ["lunar new year parade", "winter community fest"],
      march: ["st patricks parade", "spring festival weekend"],
      april: ["spring festival", "neighborhood celebration"],
      may: ["memorial day parade", "folklife festival"],
      june: ["pride festival", "summer solstice celebration"],
      july: ["summer festival", "fourth of july fireworks"],
      august: ["local food festival", "summer street fair"],
      september: ["labor day arts festival", "harvest celebration"],
      october: ["oktoberfest", "pumpkin festival"],
      november: ["holiday market", "veterans day ceremony"],
      december: ["holiday market", "holiday lights event"]
    },
    mountain: {
      january: ["new year fireworks", "winter snow carnival"],
      february: ["winter carnival", "mountain winter festival"],
      march: ["spring ski festival", "closing day party"],
      april: ["spring mountain festival", "earth day cleanup"],
      may: ["memorial day parade", "spring village market"],
      june: ["mountain games weekend", "music festival"],
      july: ["fourth of july celebration", "summer village festival"],
      august: ["summer concert series", "mountain art festival"],
      september: ["mountain film festival", "harvest festival weekend"],
      october: ["oktoberfest", "fall foliage festival"],
      november: ["holiday events", "veterans day ceremony"],
      december: ["holiday festival", "tree lighting ceremony"]
    },
    desert_southwest: {
      january: ["winter festival", "desert community festival"],
      february: ["spring training events", "rodeo season events"],
      march: ["spring training events", "spring festival"],
      april: ["food festival", "earth day celebration"],
      may: ["cinco de mayo celebration", "memorial day festival"],
      june: ["summer solstice gathering", "juneteenth community festival"],
      july: ["fourth of july fireworks", "summer evening events"],
      august: ["monsoon season festivals", "summer night market"],
      september: ["fall harvest festival", "cultural independence celebration"],
      october: ["fall procession", "day of the dead celebration"],
      november: ["day of the dead events", "veterans day ceremony"],
      december: ["holiday lights festival", "holiday luminarias walk"]
    },
    gulf_coast: {
      january: ["winter waterfront festival", "local winter celebration"],
      february: ["mardi gras parades", "parade season"],
      march: ["st patricks parade", "spring street festival"],
      april: ["historic quarter festival", "jazz and heritage fest"],
      may: ["memorial day waterfront festival", "crawfish boil festival"],
      june: ["juneteenth community festival", "summer solstice event"],
      july: ["music and culture festival", "riverfront celebration"],
      august: ["summer music weekend", "cultural heritage events"],
      september: ["labor day celebration", "fall festival"],
      october: ["fall music festival", "halloween event"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["holiday riverfront celebration", "holiday lights event"]
    },
    atlantic_south: {
      january: ["new year beach celebration", "winter coastal festival"],
      february: ["coastal film festival", "winter arts celebration"],
      march: ["st patricks beach parade", "spring street festival"],
      april: ["spring music festival", "earth day beach cleanup"],
      may: ["memorial day beach events", "cinco de mayo celebration"],
      june: ["juneteenth coastal festival", "summer solstice beach party"],
      july: ["fourth of july beach fireworks", "summer boardwalk festival"],
      august: ["late summer beach festival", "oceanfront concert series"],
      september: ["fall harvest festival", "seafood celebration"],
      october: ["fall film festival", "autumn coastal festival"],
      november: ["thanksgiving beach gathering", "veterans day ceremony"],
      december: ["holiday beachfront celebration", "holiday lights walk"]
    },
    mid_atlantic: {
      january: ["new year city celebration", "winter downtown festival"],
      february: ["lunar new year parade", "winter street fest"],
      march: ["st patricks parade", "spring festival events"],
      april: ["cherry blossom festival", "spring street festival"],
      may: ["memorial day festival", "cinco de mayo celebration"],
      june: ["pride parade and festival", "juneteenth community festival"],
      july: ["fourth of july celebration", "summer waterfront festival"],
      august: ["summer neighborhood festivals", "street fair series"],
      september: ["fall neighborhood festival", "city street festival"],
      october: ["food festival", "oktoberfest celebration"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["tree lighting", "downtown holiday market"]
    },
    new_england: {
      january: ["first night celebration", "winter coastal festival"],
      february: ["lunar new year celebration", "winter town carnival"],
      march: ["st patricks parade", "early spring festival"],
      april: ["spring holiday events", "city marathon weekend"],
      may: ["memorial day parade", "spring flower festival"],
      june: ["pride festival", "juneteenth community festival"],
      july: ["harbor festival", "fourth of july concert"],
      august: ["summer concert series", "folk music festival"],
      september: ["fall harvest festival", "apple harvest celebration"],
      october: ["fall festival", "jack o lantern festival"],
      november: ["thanksgiving celebration", "veterans day ceremony"],
      december: ["holiday countdown", "holiday stroll"]
    },
    great_lakes: {
      january: ["new year city celebration", "winter lakefront festival"],
      february: ["lunar new year celebration", "winter snow carnival"],
      march: ["st patricks river event", "spring downtown festival"],
      april: ["spring lakefront festival", "earth day lakefront cleanup"],
      may: ["memorial day parade", "cinco de mayo street festival"],
      june: ["pride parade and festival", "juneteenth lakefront festival"],
      july: ["food and music festival", "fourth of july pier fireworks"],
      august: ["summer music festival", "air and water show"],
      september: ["fall lakefront celebration", "harvest festival"],
      october: ["oktoberfest celebration", "fall neighborhood festival"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["holiday market", "downtown tree lighting"]
    },
    california: {
      january: ["new year parade", "winter street festival"],
      february: ["lunar new year parade", "coastal film festival"],
      march: ["st patricks parade", "spring arts festival"],
      april: ["earth day celebration", "spring music and arts festival"],
      may: ["cinco de mayo celebration", "spring city race"],
      june: ["pride parade and festival", "juneteenth community events"],
      july: ["fourth of july pier fireworks", "summer beach festival"],
      august: ["summer music festival", "state fair season"],
      september: ["fall harvest celebration", "art and wine festival"],
      october: ["air show weekend", "fall music festival"],
      november: ["day of the dead celebration", "veterans day ceremony"],
      december: ["holiday tree lighting", "holiday lights festival"]
    },
    hawaii: {
      january: ["lunar new year celebration", "winter island festival"],
      february: ["whale day festival", "cherry blossom celebration"],
      march: ["island cultural festival", "spring holiday events"],
      april: ["hula festival", "earth day celebration"],
      may: ["lei day celebration", "memorial day events"],
      june: ["king day events", "summer solstice celebration"],
      july: ["fourth of july fireworks", "summer island festival"],
      august: ["statehood day events", "bon dance festival"],
      september: ["aloha festivals", "fall island celebration"],
      october: ["food and wine festival", "fall harvest events"],
      november: ["coffee harvest festival", "veterans day ceremony"],
      december: ["city marathon weekend", "holiday luau celebration"]
    },
    alaska: {
      january: ["winter festival", "winter snow festival"],
      february: ["winter festival", "sled race events"],
      march: ["sled race ceremonial start", "spring carnival festival"],
      april: ["folk music festival", "spring community events"],
      may: ["memorial day festival", "heritage festival"],
      june: ["midnight sun festival", "summer solstice celebration"],
      july: ["fourth of july events", "heritage days"],
      august: ["state fair", "berry festival"],
      september: ["fall community festival", "marathon weekend"],
      october: ["alaska day celebration", "fall events"],
      november: ["heritage month events", "veterans day ceremony"],
      december: ["holiday festival", "winter events"]
    }
  },

  dining: {
    pacific_northwest: {
      january: ["local salmon dinner", "seafood boil"],
      february: ["valentines oyster bar", "salmon tasting menu"],
      march: ["salmon chowder", "farm to table dinner"],
      april: ["spring pasta special", "seafood special"],
      may: ["seasonal seafood menu", "mushroom dinner"],
      june: ["local salmon dinner", "waterfront oyster happy hour"],
      july: ["grilled salmon patio dining", "local oyster raw bar"],
      august: ["seafood platter", "patio seafood dinner"],
      september: ["mushroom tasting", "fall salmon menu"],
      october: ["chowder night", "fall mushroom dinner"],
      november: ["holiday seafood menu", "cozy fish dinner"],
      december: ["seafood feast", "holiday seafood dinner"]
    },
    mountain: {
      january: ["mountain steak dinner", "bison burger gastropub"],
      february: ["valentines steakhouse", "lodge fondue night"],
      march: ["comfort food dinner", "skillet dinner"],
      april: ["spring lamb menu", "river trout dinner"],
      may: ["patio bison burger", "smoked trout salad"],
      june: ["grilled trout dinner", "mountain barbecue patio"],
      july: ["mountain BBQ platter", "chili and craft beer"],
      august: ["sausage sampler", "mountain steak patio dining"],
      september: ["hearty stew dinner", "fall menu special"],
      october: ["pot roast dinner", "pumpkin ale night"],
      november: ["holiday roast dinner", "fireplace mountain fare"],
      december: ["prime rib dinner", "cheese fondue night"]
    },
    desert_southwest: {
      january: ["BBQ dinner", "patio carne asada"],
      february: ["valentines rooftop margaritas", "romantic dinner"],
      march: ["chile enchiladas", "sonoran hot dog dinner"],
      april: ["patio tacos", "grilled steak dinner"],
      may: ["sunset rooftop tacos", "table-side guacamole dinner"],
      june: ["indoor chile relleno dinner", "air conditioned taco bar"],
      july: ["mezcal cocktail bar", "taco night"],
      august: ["monsoon patio dining", "red chile pork dinner"],
      september: ["BBQ dinner", "street taco happy hour"],
      october: ["fall dinner menu", "BBQ cookout"],
      november: ["southwestern turkey dinner", "holiday side dishes"],
      december: ["tamale holiday dinner", "posole holiday menu"]
    },
    gulf_coast: {
      january: ["seafood gumbo", "oyster po boy dinner"],
      february: ["mardi gras prix fixe", "crawfish etouffee dinner"],
      march: ["crawfish boil patio", "shrimp po boy shop"],
      april: ["creole restaurant", "blackened fish dinner"],
      may: ["boiled crawfish platter", "chargrilled oysters patio"],
      june: ["shrimp and grits dinner", "seafood boil bucket"],
      july: ["fried catfish plate", "crab boil"],
      august: ["creole bistro", "seafood gumbo and rice"],
      september: ["redfish special", "cool weather oyster bar"],
      october: ["seafood jambalaya dinner", "fall sausage plate"],
      november: ["holiday turkey dinner", "holiday special"],
      december: ["holiday creole menu", "pecan praline dessert"]
    },
    atlantic_south: {
      january: ["crab soup dinner", "shrimp and grits"],
      february: ["valentines waterfront seafood", "romantic oyster bar"],
      march: ["lowcountry boil dinner", "spring crab menu"],
      april: ["soft shell crab season", "lowcountry cuisine"],
      may: ["small plates and pimento cheese", "fried green tomato starter"],
      june: ["waterfront shrimp and grits", "crab cake dinner"],
      july: ["summer lowcountry boil", "peach cobbler dessert"],
      august: ["red rice and shrimp dinner", "crab house dinner"],
      september: ["shrimp and okra gumbo", "porch dining"],
      october: ["oyster roast patio", "fall lowcountry menu"],
      november: ["holiday seafood spread", "holiday side dishes"],
      december: ["holiday oyster roast", "crab cake dinner"]
    },
    mid_atlantic: {
      january: ["local bistro", "cozy bistro dinner"],
      february: ["valentines waterfront bistro", "romantic wine bar dinner"],
      march: ["spring themed menu", "seasonal fish dinner"],
      april: ["crab cake dinner", "spring oyster bar"],
      may: ["memorial day crab house", "steamed shrimp"],
      june: ["rooftop crab feast", "waterfront raw bar"],
      july: ["blue crab feast", "boardwalk crab shack"],
      august: ["late summer soft shell crab", "waterfront dinner"],
      september: ["fish and crab special", "harborfront dining"],
      october: ["oyster pairing dinner", "crab dip appetizer"],
      november: ["harbor view dinner", "crab and corn chowder"],
      december: ["holiday prix fixe", "seasonal seafood tower"]
    },
    new_england: {
      january: ["clam chowder dinner", "baked haddock plate"],
      february: ["valentines harbor view dining", "lobster mac and cheese"],
      march: ["maple glazed salmon", "corned beef and cabbage dinner"],
      april: ["fried clams", "spring seafood bake"],
      may: ["lobster roll dinner", "memorial day shore dinner"],
      june: ["lobster bake", "stuffed quahog clams"],
      july: ["clambake on the beach", "lobster dinner"],
      august: ["late summer lobster feast", "clam shack dinner"],
      september: ["apple cider braised pork", "seafood chowder and biscuits"],
      october: ["pumpkin bisque and scallops", "fall tavern dinner"],
      november: ["thanksgiving turkey dinner", "roast root vegetables"],
      december: ["holiday seafood meal", "holiday lobster dinner"]
    },
    great_lakes: {
      january: ["deep dish pizza dinner", "pierogi and sausage plate"],
      february: ["valentines steakhouse", "fireplace wine bar"],
      march: ["corned beef and cabbage pub", "fish fry"],
      april: ["perch fry dinner", "spring lakefront gastropub"],
      may: ["beer garden", "memorial day lakefront grill"],
      june: ["fish fry patio", "waterfront burger bar"],
      july: ["rooftop barbecue platter", "cheese curds and beer"],
      august: ["late summer lakefront grill", "walleye dinner special"],
      september: ["oktoberfest dinner", "beer hall pretzel and stein"],
      october: ["harvest pasta dinner", "comfort food casserole"],
      november: ["thanksgiving turkey dinner", "cozy supper club dining"],
      december: ["holiday prime rib", "holiday dinner out"]
    },
    california: {
      january: ["seafood stew", "winter citrus salad menu"],
      february: ["valentines wine pairing", "romantic coastal seafood"],
      march: ["spring tasting menu", "tri tip dinner"],
      april: ["patio tapas", "small plates dinner"],
      may: ["memorial day seafood grill", "vineyard steak dinner"],
      june: ["summer wine dinner", "oceanfront fish tacos"],
      july: ["beachside fish taco stand", "sushi dinner"],
      august: ["tomato tasting menu", "late summer patio wine dinner"],
      september: ["harvest winemaker dinner", "braised short ribs"],
      october: ["pumpkin gnocchi", "fall coastal chowder"],
      november: ["wine country dinner", "duck dinner"],
      december: ["holiday tasting menu", "seafood cioppino"]
    },
    hawaii: {
      january: ["poke bowl dinner", "garlic shrimp plate"],
      february: ["valentines oceanfront seafood", "sunset poke and wine"],
      march: ["teriyaki plate lunch dinner", "loco moco comfort dinner"],
      april: ["island-style fish tacos", "kalua pork plate"],
      may: ["lei day special menu", "grilled mahi mahi dinner"],
      june: ["sunset beachfront seafood platter", "huli huli chicken dinner"],
      july: ["oceanfront ahi steak", "tropical fruit dessert menu"],
      august: ["late summer poke flight", "waterfront dinner"],
      september: ["shoyu chicken dinner", "local plate lunch evening"],
      october: ["island food and wine menu", "poke and sashimi platter"],
      november: ["holiday turkey dinner", "hawaiian-style buffet dinner"],
      december: ["holiday luau buffet", "holiday prime rib dinner"]
    },
    alaska: {
      january: ["king crab dinner", "salmon chowder and sourdough"],
      february: ["valentines seafood dinner", "sausage entree"],
      march: ["smoked salmon platter", "hearty stew"],
      april: ["halibut dinner", "cod fish and chips"],
      may: ["halibut special", "dockside seafood grill"],
      june: ["salmon barbecue", "waterfront crab boil"],
      july: ["grilled salmon dinner", "seafood combo platter"],
      august: ["fresh salmon menu", "black cod entree"],
      september: ["hearty stew", "fall seafood chowder"],
      october: ["meatloaf dinner", "cozy lodge comfort food"],
      november: ["holiday seafood and game", "crab bisque starter"],
      december: ["holiday crab dinner", "lodge dining"]
    }
  },

  coffee_brunch: {
    pacific_northwest: {
      january: ["cozy coffee shop", "single origin pour over"],
      february: ["valentines brunch", "romantic cafe"],
      march: ["spring cafe patio", "coffee roastery tour"],
      april: ["spring patio cafe", "outdoor espresso bar"],
      may: ["memorial day brunch", "patio latte and pastry"],
      june: ["summer brunch", "cold brew flight"],
      july: ["iced latte", "patio cafe"],
      august: ["late summer brunch bowl", "waterfront coffee seating"],
      september: ["maple latte", "pumpkin spice coffee"],
      october: ["pumpkin spice latte", "fall brunch"],
      november: ["cozy coffee shop", "holiday spice latte preview"],
      december: ["holiday latte", "peppermint mocha seasonal"]
    },
    mountain: {
      january: ["cozy mountain cafe", "hot chocolate apres"],
      february: ["valentines mountain brunch", "romantic fireside cafe"],
      march: ["spring ski town brunch", "cabin style cafe"],
      april: ["mountain view cafe", "hearty breakfast"],
      may: ["memorial day mountain brunch", "outdoor cafe opens"],
      june: ["summer brunch", "mountain view patio coffee"],
      july: ["mountain cafe patio", "cold brew after hike"],
      august: ["late summer trailhead brunch", "outdoor coffee with views"],
      september: ["fall mountain cafe", "pumpkin spice latte"],
      october: ["maple cinnamon latte", "fall brunch"],
      november: ["thanksgiving brunch buffet", "lodge style cafe"],
      december: ["holiday brunch", "cozy lodge cafe"]
    },
    desert_southwest: {
      january: ["sunny patio cafe", "outdoor cortado"],
      february: ["valentines brunch patio", "mimosa brunch"],
      march: ["spring brunch", "patio coffee and chilaquiles"],
      april: ["courtyard cafe", "patio brunch huevos rancheros"],
      may: ["early morning cafe", "sunrise iced latte"],
      june: ["early morning cold brew", "air conditioned espresso bar"],
      july: ["sunrise coffee on patio", "indoor cafe"],
      august: ["early morning brunch tacos", "indoor cafe wi-fi"],
      september: ["patio season returns", "outdoor cafe sunrise"],
      october: ["perfect patio weather", "fall brunch"],
      november: ["comfortable patio coffee", "thanksgiving weekend brunch"],
      december: ["holiday brunch patio", "holiday horchata latte"]
    },
    gulf_coast: {
      january: ["cozy cafe", "beignets cafe"],
      february: ["mardi gras brunch", "king cake latte"],
      march: ["spring cafe patio", "chicory coffee and beignets"],
      april: ["spring patio cafe", "jazz brunch"],
      may: ["memorial day brunch", "patio cafe with live music"],
      june: ["summer brunch", "outdoor cafe by the river"],
      july: ["indoor cafe", "iced chicory coffee"],
      august: ["air conditioned cafe", "cold brew chicory"],
      september: ["fall cafe by the bayou", "comfortable patio beignets"],
      october: ["fall brunch shrimp and grits", "pumpkin beignets"],
      november: ["cozy cafe with pralines", "thanksgiving weekend brunch"],
      december: ["holiday brunch with beignets", "holiday cafe drinks"]
    },
    atlantic_south: {
      january: ["cozy beach town cafe", "winter coastal coffee"],
      february: ["valentines brunch", "marsh view cafe"],
      march: ["spring patio cafe", "porch swing coffee"],
      april: ["beach cafe spring", "patio sweet tea and latte"],
      may: ["memorial day beach brunch", "beach cafe biscuits"],
      june: ["summer brunch", "beachfront acai bowl cafe"],
      july: ["beach coffee morning", "iced sweet cream cold brew"],
      august: ["late summer brunch", "beach cafe beignets"],
      september: ["comfortable patio cafe", "fall brunch"],
      october: ["pumpkin spice on the porch", "fall beach brunch"],
      november: ["cozy beach cafe", "thanksgiving weekend brunch"],
      december: ["holiday beach brunch", "holiday coastal cafe"]
    },
    mid_atlantic: {
      january: ["cozy neighborhood cafe", "winter specialty latte"],
      february: ["valentines brunch", "romantic city cafe"],
      march: ["spring cafe", "cherry blossom brunch"],
      april: ["spring patio cafe", "cherry blossom latte"],
      may: ["memorial day brunch", "patio cafe along the river"],
      june: ["summer brunch", "outdoor cafe"],
      july: ["patio cafe summer", "iced coffee on the waterfront"],
      august: ["late summer brunch", "outdoor cafe"],
      september: ["fall patio cafe", "autumn spice latte"],
      october: ["pumpkin spice latte", "fall brunch in historic district"],
      november: ["cozy cafe with books", "thanksgiving brunch"],
      december: ["holiday brunch", "holiday cafe drinks"]
    },
    new_england: {
      january: ["cozy harbor cafe", "hot chocolate with whipped cream"],
      february: ["valentines brunch", "romantic harborview cafe"],
      march: ["spring cafe", "maple latte"],
      april: ["spring harbor cafe", "maple treat stop"],
      may: ["memorial day brunch", "outdoor harbor cafe"],
      june: ["summer brunch", "harbor cafe patio"],
      july: ["waterfront cafe", "iced coffee by the docks"],
      august: ["late summer brunch", "harbor cafe brunch"],
      september: ["fall harbor cafe", "apple cider donut stop"],
      october: ["pumpkin spice latte", "apple cider brunch"],
      november: ["cozy cafe", "maple hot chocolate"],
      december: ["holiday brunch", "holiday hot chocolate"]
    },
    great_lakes: {
      january: ["cozy lakefront cafe", "winter latte"],
      february: ["valentines brunch downtown", "romantic cafe"],
      march: ["spring cafe", "st patricks brunch and coffee"],
      april: ["spring lakefront cafe", "patio opening weekend"],
      may: ["memorial day brunch", "lakefront patio coffee"],
      june: ["summer brunch", "lakefront cafe"],
      july: ["outdoor lakefront brunch", "iced coffee by the pier"],
      august: ["late summer brunch", "lakefront cafe waffles"],
      september: ["fall lakefront cafe", "maple and caramel latte"],
      october: ["pumpkin spice lakefront", "fall brunch"],
      november: ["cozy cafe", "thanksgiving brunch"],
      december: ["holiday brunch", "holiday lakefront cafe"]
    },
    california: {
      january: ["coastal cafe", "farm fresh brunch"],
      february: ["valentines brunch", "wine country cafe"],
      march: ["spring avocado toast brunch", "patio cafe"],
      april: ["spring cafe with citrus", "farm to table brunch"],
      may: ["memorial day brunch", "outdoor beach cafe"],
      june: ["summer brunch", "beach cafe smoothies"],
      july: ["coastal cafe summer", "nitro cold brew bar"],
      august: ["late summer brunch with berries", "beach cafe acai bowls"],
      september: ["fall cafe", "wine country brunch"],
      october: ["pumpkin spice in wine country", "fall brunch on patio"],
      november: ["thanksgiving weekend brunch", "farm to table cafe"],
      december: ["holiday coastal brunch", "holiday coastal cafe"]
    },
    hawaii: {
      january: ["beach cafe", "kona coffee pour over"],
      february: ["valentines brunch", "ocean view cafe acai bowls"],
      march: ["spring brunch", "beach cafe loco moco"],
      april: ["tropical cafe", "fresh juice bar"],
      may: ["memorial day brunch", "beach cafe pancakes with coconut"],
      june: ["summer brunch", "ocean cafe latte with macadamia milk"],
      july: ["beach cafe morning", "tropical iced coffee"],
      august: ["oceanfront cafe", "kona cold brew"],
      september: ["beach cafe", "island style coffee"],
      october: ["pumpkin spice with coconut", "fall tropical brunch"],
      november: ["thanksgiving brunch island", "ocean cafe malasadas"],
      december: ["holiday brunch beach", "holiday island cafe"]
    },
    alaska: {
      january: ["cozy winter cafe", "hot chocolate after aurora"],
      february: ["valentines brunch", "romantic cabin cafe"],
      march: ["spring brunch", "sled race morning coffee"],
      april: ["spring cafe", "local roaster pour over"],
      may: ["memorial day brunch", "outdoor cafe starts"],
      june: ["midnight sun cafe", "late daylight patio coffee"],
      july: ["outdoor cafe summer", "cold brew in midnight sun"],
      august: ["late summer brunch", "outdoor cafe"],
      september: ["fall cafe", "spiced latte before aurora"],
      october: ["pumpkin spice season", "fall brunch"],
      november: ["cozy cafe", "hot chocolate"],
      december: ["holiday brunch", "winter cafe"]
    }
  },

  nightlife_social: {
    pacific_northwest: {
      january: ["cozy craft beer pub", "whiskey bar"],
      february: ["valentines cocktail bar", "romantic lounge"],
      march: ["spring beer garden opening", "irish pub with live music"],
      april: ["spring rooftop taproom", "cocktail bar"],
      may: ["memorial day rooftop brewery", "craft beer night"],
      june: ["summer brewery patio", "rooftop bar season"],
      july: ["waterfront beer garden", "rooftop cocktail bar"],
      august: ["late summer rooftop pints", "outdoor cider house"],
      september: ["fall seasonal ale taphouse", "whiskey bar"],
      october: ["oktoberfest beer hall", "fall beer release"],
      november: ["cozy neighborhood lounge", "whiskey bar"],
      december: ["holiday cocktail pop up", "new years eve party"]
    },
    mountain: {
      january: ["apres ski bar", "fireplace lodge lounge"],
      february: ["valentines wine bar", "fireside cocktails"],
      march: ["ski town bar", "closing day patio party"],
      april: ["spring lodge bar", "mountain whiskey lounge"],
      may: ["outdoor beer garden", "patio cider bar"],
      june: ["mountaintop bar", "mountain rooftop cocktails"],
      july: ["brewery beer garden", "live music bar"],
      august: ["riverside bar", "mountain cocktail lounge"],
      september: ["fall lodge lounge", "whiskey bar"],
      october: ["oktoberfest tent", "fall craft beer bar"],
      november: ["fireplace bourbon bar", "ski film night pub"],
      december: ["holiday lodge bar", "new year countdown"]
    },
    desert_southwest: {
      january: ["heated patio margarita bar", "outdoor firepit lounge"],
      february: ["valentines rooftop tequila bar", "romantic lounge"],
      march: ["spring patio bar", "tequila and mezcal bar"],
      april: ["rooftop cocktail bar", "patio paloma night"],
      may: ["sunset patio drinks", "outdoor cantina bar"],
      june: ["indoor speakeasy", "late night tequila lounge"],
      july: ["cool indoor cocktail bar", "evening rooftop breeze"],
      august: ["indoor mezcal lounge", "storm view bar"],
      september: ["patio season returns", "outdoor cantina patio"],
      october: ["perfect patio weather bar", "fall themed bar"],
      november: ["starry night patio bar", "tequila and taco bar"],
      december: ["holiday rooftop bar", "holiday lounge"]
    },
    gulf_coast: {
      january: ["cozy cajun bar", "jazz lounge"],
      february: ["mardi gras balcony bar", "hurricane cocktail bar"],
      march: ["spring patio bar", "irish pub with live band"],
      april: ["jazz fest after show bar", "spring courtyard cocktails"],
      may: ["memorial day riverfront bar", "patio daiquiri bar"],
      june: ["summer rooftop bar", "live blues bar"],
      july: ["outdoor cajun bar", "live music venue"],
      august: ["air conditioned jazz club", "cocktail bar in historic district"],
      september: ["fall patio cocktail bar", "whiskey and rye bar"],
      october: ["halloween themed bar", "costume party bar"],
      november: ["cozy bourbon lounge", "old fashioned whiskey bar"],
      december: ["holiday cocktail bar", "holiday cocktail menu"]
    },
    atlantic_south: {
      january: ["cozy coastal bar", "winter bourbon cocktails"],
      february: ["valentines beach cocktail bar", "romantic rooftop lounge"],
      march: ["spring beach tiki bar", "st patricks pub crawl"],
      april: ["spring pier bar", "ocean view cocktail bar"],
      may: ["memorial day beach bar", "rooftop harbor bar"],
      june: ["summer beach party bar", "beach bar peak season"],
      july: ["outdoor beach bar with live band", "summer tiki lounge"],
      august: ["late summer beach rooftop", "harbor view bar"],
      september: ["fall patio oyster bar", "outdoor cocktails"],
      october: ["fall beach firepit bar", "oktoberfest beer night"],
      november: ["cozy beach whiskey lounge", "bourbon and rye bar"],
      december: ["holiday beach bar lights", "holiday coastal party"]
    },
    mid_atlantic: {
      january: ["cozy historic bar", "downtown speakeasy"],
      february: ["valentines cocktail lounge", "romantic wine bar"],
      march: ["spring city pub night", "irish pub with live music"],
      april: ["spring rooftop opens", "patio cocktail bar"],
      may: ["memorial day rooftop happy hour", "beer garden with string lights"],
      june: ["summer rooftop bar", "rooftop peak season"],
      july: ["rooftop bar", "outdoor beer garden"],
      august: ["late summer rooftop cocktails", "beer garden picnic tables"],
      september: ["fall beer garden", "whiskey bar"],
      october: ["oktoberfest stein night", "fall craft cocktail lounge"],
      november: ["cozy lounge", "bourbon and cigar bar"],
      december: ["holiday party bar", "holiday cocktail pop up"]
    },
    new_england: {
      january: ["cozy harbor tavern", "fireplace whiskey lounge"],
      february: ["valentines harborview lounge", "romantic fireplace bar"],
      march: ["spring neighborhood bar", "irish pub with live music"],
      april: ["spring harbor bar", "waterfront patio bar opens"],
      may: ["memorial day harbor rooftop", "outdoor dock bar"],
      june: ["summer harbor bar", "harbor rooftop cocktails"],
      july: ["waterfront bar", "rooftop summer drinks"],
      august: ["late summer harbor patio", "rooftop gin bar"],
      september: ["fall harbor lounge", "whiskey bar"],
      october: ["halloween costume bar night", "oktoberfest beer hall"],
      november: ["cozy fireplace bar", "bourbon and maple cocktails"],
      december: ["holiday harbor bar", "holiday cocktail lounge"]
    },
    great_lakes: {
      january: ["cozy lakefront bar", "winter craft cocktails"],
      february: ["valentines downtown lounge", "romantic wine and cocktail bar"],
      march: ["spring bar night", "st patricks riverfront pub"],
      april: ["spring lakefront bar", "patio opens for beers"],
      may: ["memorial day lakefront bar", "outdoor beer garden"],
      june: ["summer bar", "lakefront rooftop cocktails"],
      july: ["rooftop bar with skyline view", "lakefront beach bar"],
      august: ["late summer lakefront drinks", "outdoor patio bar"],
      september: ["fall lakefront bar", "oktoberfest beer garden"],
      october: ["oktoberfest stein specials", "fall whiskey lounge"],
      november: ["cozy neighborhood lounge", "whiskey and rye bar"],
      december: ["holiday party bar", "holiday lakefront cocktail bar"]
    },
    california: {
      january: ["coastal wine bar", "beach town cocktail lounge"],
      february: ["valentines wine bar", "romantic coastal lounge"],
      march: ["spring rooftop bar", "beer garden in the sun"],
      april: ["spring patio bar", "wine tasting room night"],
      may: ["memorial day rooftop party", "beach bar sunset drinks"],
      june: ["summer rooftop bar", "oceanfront tiki bar"],
      july: ["beach bar summer night", "rooftop cocktail lounge"],
      august: ["late summer rooftop sunset", "beach bar with live DJ"],
      september: ["fall wine bar", "rooftop wine flights"],
      october: ["wine harvest celebration", "craft cocktail lounge"],
      november: ["cozy coastal lounge", "bourbon and wine bar"],
      december: ["holiday rooftop party", "holiday cocktail bar"]
    },
    hawaii: {
      january: ["beach bar sunset", "tiki bar mai tai night"],
      february: ["valentines beach bar", "romantic oceanfront lounge"],
      march: ["spring beach bar", "tiki lounge with live music"],
      april: ["tropical cocktail lounge", "beachfront rum bar"],
      may: ["memorial day beach bar", "tiki bar with live music"],
      june: ["summer beach party", "beach bar peak season"],
      july: ["tiki lounge summer", "beach bar with live music"],
      august: ["late summer beach bar", "tropical drinks happy hour"],
      september: ["sunset beach bar", "island tiki lounge"],
      october: ["tropical halloween party", "tiki bar costume night"],
      november: ["thanksgiving beach bar", "island cocktail lounge"],
      december: ["holiday beach bar lights", "holiday tropical cocktail bar"]
    },
    alaska: {
      january: ["winter lodge bar", "cozy fireplace lounge"],
      february: ["valentines lodge bar", "winter party bar"],
      march: ["sled race celebration bar", "cozy pub with live music"],
      april: ["spring lodge bar", "local brewery taproom"],
      may: ["outdoor deck bar opens", "midnight sun cocktails"],
      june: ["midnight sun bar", "outdoor riverside lounge"],
      july: ["midnight sun rooftop", "outdoor bar peak season"],
      august: ["late summer harbor bar", "outdoor lounge by the water"],
      september: ["fall lounge", "whiskey bar"],
      october: ["fall bar night", "cocktail lounge"],
      november: ["winter whiskey lounge", "bourbon bar"],
      december: ["holiday bar party", "holiday lounge"]
    }
  }
}
