export const ATTRACTIONS_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["public market", "art museum"],
      february: ["food and wine festival", "chocolate tour"],
      march: ["spring market", "farmers market"],
      april: ["tulip festival", "brewery tour"],
      may: ["farmers market", "brewery tour"],
      june: ["summer market", "open-air market"],
      july: ["summer festival", "street market"],
      august: ["summer festival", "sand sculpture festival"],
      september: ["harvest festival", "fall brewery tour"],
      october: ["oktoberfest celebration", "fall festival"],
      november: ["holiday market preview", "seafood festival"],
      december: ["holiday market", "holiday lights display"]
    },
    mountain: {
      january: ["mountain hot springs", "scenic winter railway"],
      february: ["hot springs soak", "resort spa"],
      march: ["hot springs visit", "national park visitor center"],
      april: ["heritage train ride", "spring mountain resort"],
      may: ["scenic mountain railroad", "alpine hot springs"],
      june: ["mountain games festival", "summer scenic railway"],
      july: ["mountain music festival", "hot springs evening soak"],
      august: ["scenic train ride", "mountain hot springs"],
      september: ["fall foliage train", "hot springs fall visit"],
      october: ["fall foliage train ride", "mountain hot springs"],
      november: ["scenic railway", "cozy hot springs getaway"],
      december: ["holiday train ride", "winter hot springs visit"]
    },
    desert_southwest: {
      january: ["natural history museum", "cultural museum"],
      february: ["botanical garden", "heritage museum"],
      march: ["spring botanical garden", "historic mission site"],
      april: ["botanical garden bloom walk", "caverns tour"],
      may: ["morning museum visit", "heritage site tour"],
      june: ["architectural walking tour", "indoor museum"],
      july: ["caverns tour", "history museum"],
      august: ["museum visit", "historic site"],
      september: ["fall botanical garden", "heritage walking tours"],
      october: ["botanical garden evening", "fall procession event"],
      november: ["heritage museum", "historic district tour"],
      december: ["holiday garden walk", "holiday lights event"]
    },
    gulf_coast: {
      january: ["aquarium visit", "historic district walk"],
      february: ["parade route", "historic district tour"],
      march: ["spring parade", "plantation tour"],
      april: ["spring festival", "aquarium visit"],
      may: ["zoo visit", "aquarium peak season"],
      june: ["summer aquarium visit", "historic house tour"],
      july: ["aquarium visit", "historic walking tour"],
      august: ["aquarium visit", "historic district tour"],
      september: ["fall aquarium visit", "heritage festival"],
      october: ["zoo event", "historic ghost tour"],
      november: ["heritage event", "historic district stroll"],
      december: ["holiday lights festival", "holiday riverfront events"]
    },
    atlantic_south: {
      january: ["lighthouse overlook", "ocean aquarium"],
      february: ["lighthouse tour", "fishing pier walk"],
      march: ["spring lighthouse visit", "pier season opening"],
      april: ["lighthouse tour", "pier activities"],
      may: ["memorial day lighthouse visit", "pier rides and games"],
      june: ["summer lighthouse tours", "pier attractions"],
      july: ["lighthouse tour", "pier summer festival"],
      august: ["late summer lighthouse stop", "pier summer activities"],
      september: ["fall lighthouse visit", "fall pier events"],
      october: ["lighthouse tour", "fall pier festival"],
      november: ["lighthouse visit", "quiet pier walk"],
      december: ["holiday lighthouse lights", "holiday pier light display"]
    },
    mid_atlantic: {
      january: ["museums visit", "maritime museum"],
      february: ["museum weekend", "history museum"],
      march: ["cherry blossom preview walk", "spring maritime museum"],
      april: ["cherry blossom festival", "tidal basin walk"],
      may: ["monuments tour", "boardwalk season opening"],
      june: ["summer boardwalk", "museum visit"],
      july: ["national mall visit", "boardwalk peak season"],
      august: ["late summer boardwalk night", "museum visit"],
      september: ["fall museum visits", "fall boardwalk stroll"],
      october: ["museum weekend", "harvest-themed boardwalk"],
      november: ["museum weekend", "late fall maritime museum"],
      december: ["holiday tree display", "holiday maritime display"]
    },
    new_england: {
      january: ["winter lighthouse visit", "maritime museum"],
      february: ["lighthouse winter visit", "local history museum"],
      march: ["maple sugar house tour", "spring lighthouse visit"],
      april: ["lighthouse spring tour", "harbor cruise season opens"],
      may: ["memorial day lighthouse visit", "harbor sightseeing tours"],
      june: ["summer lighthouse tour", "historic harbor walk"],
      july: ["lighthouse summer festival", "harbor tour peak season"],
      august: ["late summer lighthouse stop", "harbor tours"],
      september: ["fall lighthouse visit", "harbor foliage tours"],
      october: ["fall festival", "lighthouse tour"],
      november: ["maritime museum visit", "late fall lighthouse stop"],
      december: ["holiday lighthouse lights", "holiday island stroll"]
    },
    great_lakes: {
      january: ["winter lakefront walk", "natural history museum"],
      february: ["science museum visit", "city museum"],
      march: ["art museum day", "early spring lakefront walk"],
      april: ["spring lakefront walk", "brewery tour season opening"],
      may: ["memorial day lakefront visit", "brewery tour season"],
      june: ["summer lakefront", "summer brewery tour"],
      july: ["summer fireworks show", "brewery summer festival"],
      august: ["late summer lakefront evening", "brewery tour weekend"],
      september: ["fall brewery tour", "fall lakefront stroll"],
      october: ["oktoberfest brewery event", "crisp fall lakefront"],
      november: ["brewery visit", "late fall lakefront walk"],
      december: ["holiday market", "holiday brewery event"]
    },
    california: {
      january: ["coastal aquarium", "coastal wildlife viewing"],
      february: ["whale watch cruise", "almond blossom scenic tour"],
      march: ["spring winery tasting", "whale watching season"],
      april: ["barrel tasting weekend", "spring winery tour"],
      may: ["winery tour season", "mission trail walking tour"],
      june: ["summer winery picnic", "aquarium visit"],
      july: ["summer convention", "winery evening event"],
      august: ["late summer winery visit", "theme park day"],
      september: ["wine crush season", "harvest festival"],
      october: ["pumpkin harvest festival", "fall winery harvest tour"],
      november: ["winery visit", "fall harvest tasting tour"],
      december: ["holiday winery lights", "holiday theme park visit"]
    },
    hawaii: {
      january: ["whale watching tour", "luau cultural show"],
      february: ["whale festival", "whale watching season"],
      march: ["island cultural festival", "volcano sightseeing tour"],
      april: ["hula festival", "spring luau evening"],
      may: ["lei day celebration", "volcano guided tours"],
      june: ["cultural parade", "island cultural center"],
      july: ["summer luau show", "volcano summit tours"],
      august: ["bon dance festival", "volcano park visit"],
      september: ["aloha festival events", "island cultural center visit"],
      october: ["food and wine festival", "fall volcano excursion"],
      november: ["holiday luau dinner", "cultural center exhibits"],
      december: ["holiday luau show", "holiday cultural celebration"]
    },
    alaska: {
      january: ["winter scenic tour", "wildlife center visit"],
      february: ["winter festival", "wildlife viewing"],
      march: ["sled race event", "spring tour"],
      april: ["wildlife center visit", "glacier cruise preview"],
      may: ["glacier cruise", "wildlife center walk"],
      june: ["midnight sun festival", "glacier cruise season"],
      july: ["summer glacier cruise", "salmon hatchery tour"],
      august: ["bear viewing platform", "wildlife viewing tour"],
      september: ["fall glacier cruise", "early fall scenic tour"],
      october: ["fall tour", "wildlife excursions"],
      november: ["winter tour season", "heritage cultural center"],
      december: ["holiday festival", "winter scenic tour"]
    }
  }
