export const COMMUNITY_EVENTS_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["new year celebration", "winter lights festival"],
      february: ["lunar new year parade", "winter community fest"],
      march: ["st patricks parade", "spring festival weekend"],
      april: ["spring festival", "neighborhood celebration"],
      may: ["memorial day parade", "folklife festival"],
      june: ["pride festival", "summer solstice celebration"],
      july: ["summer festival", "fourth of july fireworks"],
      august: ["local food festival", "summer street fair"],
      september: ["labor day arts festival", "harvest celebration"],
      october: ["oktoberfest", "pumpkin festival"],
      november: ["holiday market", "veterans day ceremony"],
      december: ["holiday market", "holiday lights event"]
    },
    mountain: {
      january: ["new year fireworks", "winter snow carnival"],
      february: ["winter carnival", "mountain winter festival"],
      march: ["spring ski festival", "closing day party"],
      april: ["spring mountain festival", "earth day cleanup"],
      may: ["memorial day parade", "spring village market"],
      june: ["mountain games weekend", "music festival"],
      july: ["fourth of july celebration", "summer village festival"],
      august: ["summer concert series", "mountain art festival"],
      september: ["mountain film festival", "harvest festival weekend"],
      october: ["oktoberfest", "fall foliage festival"],
      november: ["holiday events", "veterans day ceremony"],
      december: ["holiday festival", "tree lighting ceremony"]
    },
    desert_southwest: {
      january: ["winter festival", "desert community festival"],
      february: ["spring training events", "rodeo season events"],
      march: ["spring training events", "spring festival"],
      april: ["food festival", "earth day celebration"],
      may: ["cinco de mayo celebration", "memorial day festival"],
      june: ["summer solstice gathering", "juneteenth community festival"],
      july: ["fourth of july fireworks", "summer evening events"],
      august: ["monsoon season festivals", "summer night market"],
      september: ["fall harvest festival", "cultural independence celebration"],
      october: ["fall procession", "day of the dead celebration"],
      november: ["day of the dead events", "veterans day ceremony"],
      december: ["holiday lights festival", "holiday luminarias walk"]
    },
    gulf_coast: {
      january: ["winter waterfront festival", "local winter celebration"],
      february: ["mardi gras parades", "parade season"],
      march: ["st patricks parade", "spring street festival"],
      april: ["historic quarter festival", "jazz and heritage fest"],
      may: ["memorial day waterfront festival", "crawfish boil festival"],
      june: ["juneteenth community festival", "summer solstice event"],
      july: ["music and culture festival", "riverfront celebration"],
      august: ["summer music weekend", "cultural heritage events"],
      september: ["labor day celebration", "fall festival"],
      october: ["fall music festival", "halloween event"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["holiday riverfront celebration", "holiday lights event"]
    },
    atlantic_south: {
      january: ["new year beach celebration", "winter coastal festival"],
      february: ["coastal film festival", "winter arts celebration"],
      march: ["st patricks beach parade", "spring street festival"],
      april: ["spring music festival", "earth day beach cleanup"],
      may: ["memorial day beach events", "cinco de mayo celebration"],
      june: ["juneteenth coastal festival", "summer solstice beach party"],
      july: ["fourth of july beach fireworks", "summer boardwalk festival"],
      august: ["late summer beach festival", "oceanfront concert series"],
      september: ["fall harvest festival", "seafood celebration"],
      october: ["fall film festival", "autumn coastal festival"],
      november: ["thanksgiving beach gathering", "veterans day ceremony"],
      december: ["holiday beachfront celebration", "holiday lights walk"]
    },
    mid_atlantic: {
      january: ["new year city celebration", "winter downtown festival"],
      february: ["lunar new year parade", "winter street fest"],
      march: ["st patricks parade", "spring festival events"],
      april: ["cherry blossom festival", "spring street festival"],
      may: ["memorial day festival", "cinco de mayo celebration"],
      june: ["pride parade and festival", "juneteenth community festival"],
      july: ["fourth of july celebration", "summer waterfront festival"],
      august: ["summer neighborhood festivals", "street fair series"],
      september: ["fall neighborhood festival", "city street festival"],
      october: ["food festival", "oktoberfest celebration"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["tree lighting", "downtown holiday market"]
    },
    new_england: {
      january: ["first night celebration", "winter coastal festival"],
      february: ["lunar new year celebration", "winter town carnival"],
      march: ["st patricks parade", "early spring festival"],
      april: ["spring holiday events", "city marathon weekend"],
      may: ["memorial day parade", "spring flower festival"],
      june: ["pride festival", "juneteenth community festival"],
      july: ["harbor festival", "fourth of july concert"],
      august: ["summer concert series", "folk music festival"],
      september: ["fall harvest festival", "apple harvest celebration"],
      october: ["fall festival", "jack o lantern festival"],
      november: ["thanksgiving celebration", "veterans day ceremony"],
      december: ["holiday countdown", "holiday stroll"]
    },
    great_lakes: {
      january: ["new year city celebration", "winter lakefront festival"],
      february: ["lunar new year celebration", "winter snow carnival"],
      march: ["st patricks river event", "spring downtown festival"],
      april: ["spring lakefront festival", "earth day lakefront cleanup"],
      may: ["memorial day parade", "cinco de mayo street festival"],
      june: ["pride parade and festival", "juneteenth lakefront festival"],
      july: ["food and music festival", "fourth of july pier fireworks"],
      august: ["summer music festival", "air and water show"],
      september: ["fall lakefront celebration", "harvest festival"],
      october: ["oktoberfest celebration", "fall neighborhood festival"],
      november: ["thanksgiving parade", "veterans day ceremony"],
      december: ["holiday market", "downtown tree lighting"]
    },
    california: {
      january: ["new year parade", "winter street festival"],
      february: ["lunar new year parade", "coastal film festival"],
      march: ["st patricks parade", "spring arts festival"],
      april: ["earth day celebration", "spring music and arts festival"],
      may: ["cinco de mayo celebration", "spring city race"],
      june: ["pride parade and festival", "juneteenth community events"],
      july: ["fourth of july pier fireworks", "summer beach festival"],
      august: ["summer music festival", "state fair season"],
      september: ["fall harvest celebration", "art and wine festival"],
      october: ["air show weekend", "fall music festival"],
      november: ["day of the dead celebration", "veterans day ceremony"],
      december: ["holiday tree lighting", "holiday lights festival"]
    },
    hawaii: {
      january: ["lunar new year celebration", "winter island festival"],
      february: ["whale day festival", "cherry blossom celebration"],
      march: ["island cultural festival", "spring holiday events"],
      april: ["hula festival", "earth day celebration"],
      may: ["lei day celebration", "memorial day events"],
      june: ["king day events", "summer solstice celebration"],
      july: ["fourth of july fireworks", "summer island festival"],
      august: ["statehood day events", "bon dance festival"],
      september: ["aloha festivals", "fall island celebration"],
      october: ["food and wine festival", "fall harvest events"],
      november: ["coffee harvest festival", "veterans day ceremony"],
      december: ["city marathon weekend", "holiday luau celebration"]
    },
    alaska: {
      january: ["winter festival", "winter snow festival"],
      february: ["winter festival", "sled race events"],
      march: ["sled race ceremonial start", "spring carnival festival"],
      april: ["folk music festival", "spring community events"],
      may: ["memorial day festival", "heritage festival"],
      june: ["midnight sun festival", "summer solstice celebration"],
      july: ["fourth of july events", "heritage days"],
      august: ["state fair", "berry festival"],
      september: ["fall community festival", "marathon weekend"],
      october: ["alaska day celebration", "fall events"],
      november: ["heritage month events", "veterans day ceremony"],
      december: ["holiday festival", "winter events"]
    }
  }
