export const DINING_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["local salmon dinner", "seafood boil"],
      february: ["valentines oyster bar", "salmon tasting menu"],
      march: ["salmon chowder", "farm to table dinner"],
      april: ["spring pasta special", "seafood special"],
      may: ["seasonal seafood menu", "mushroom dinner"],
      june: ["local salmon dinner", "waterfront oyster happy hour"],
      july: ["grilled salmon patio dining", "local oyster raw bar"],
      august: ["seafood platter", "patio seafood dinner"],
      september: ["mushroom tasting", "fall salmon menu"],
      october: ["chowder night", "fall mushroom dinner"],
      november: ["holiday seafood menu", "cozy fish dinner"],
      december: ["seafood feast", "holiday seafood dinner"]
    },
    mountain: {
      january: ["mountain steak dinner", "bison burger gastropub"],
      february: ["valentines steakhouse", "lodge fondue night"],
      march: ["comfort food dinner", "skillet dinner"],
      april: ["spring lamb menu", "river trout dinner"],
      may: ["patio bison burger", "smoked trout salad"],
      june: ["grilled trout dinner", "mountain barbecue patio"],
      july: ["mountain BBQ platter", "chili and craft beer"],
      august: ["sausage sampler", "mountain steak patio dining"],
      september: ["hearty stew dinner", "fall menu special"],
      october: ["pot roast dinner", "pumpkin ale night"],
      november: ["holiday roast dinner", "fireplace mountain fare"],
      december: ["prime rib dinner", "cheese fondue night"]
    },
    desert_southwest: {
      january: ["BBQ dinner", "patio carne asada"],
      february: ["valentines rooftop margaritas", "romantic dinner"],
      march: ["chile enchiladas", "sonoran hot dog dinner"],
      april: ["patio tacos", "grilled steak dinner"],
      may: ["sunset rooftop tacos", "table-side guacamole dinner"],
      june: ["indoor chile relleno dinner", "air conditioned taco bar"],
      july: ["mezcal cocktail bar", "taco night"],
      august: ["monsoon patio dining", "red chile pork dinner"],
      september: ["BBQ dinner", "street taco happy hour"],
      october: ["fall dinner menu", "BBQ cookout"],
      november: ["southwestern turkey dinner", "holiday side dishes"],
      december: ["tamale holiday dinner", "posole holiday menu"]
    },
    gulf_coast: {
      january: ["seafood gumbo", "oyster po boy dinner"],
      february: ["mardi gras prix fixe", "crawfish etouffee dinner"],
      march: ["crawfish boil patio", "shrimp po boy shop"],
      april: ["creole restaurant", "blackened fish dinner"],
      may: ["boiled crawfish platter", "chargrilled oysters patio"],
      june: ["shrimp and grits dinner", "seafood boil bucket"],
      july: ["fried catfish plate", "crab boil"],
      august: ["creole bistro", "seafood gumbo and rice"],
      september: ["redfish special", "cool weather oyster bar"],
      october: ["seafood jambalaya dinner", "fall sausage plate"],
      november: ["holiday turkey dinner", "holiday special"],
      december: ["holiday creole menu", "pecan praline dessert"]
    },
    atlantic_south: {
      january: ["crab soup dinner", "shrimp and grits"],
      february: ["valentines waterfront seafood", "romantic oyster bar"],
      march: ["lowcountry boil dinner", "spring crab menu"],
      april: ["soft shell crab season", "lowcountry cuisine"],
      may: ["small plates and pimento cheese", "fried green tomato starter"],
      june: ["waterfront shrimp and grits", "crab cake dinner"],
      july: ["summer lowcountry boil", "peach cobbler dessert"],
      august: ["red rice and shrimp dinner", "crab house dinner"],
      september: ["shrimp and okra gumbo", "porch dining"],
      october: ["oyster roast patio", "fall lowcountry menu"],
      november: ["holiday seafood spread", "holiday side dishes"],
      december: ["holiday oyster roast", "crab cake dinner"]
    },
    mid_atlantic: {
      january: ["local bistro", "cozy bistro dinner"],
      february: ["valentines waterfront bistro", "romantic wine bar dinner"],
      march: ["spring themed menu", "seasonal fish dinner"],
      april: ["crab cake dinner", "spring oyster bar"],
      may: ["memorial day crab house", "steamed shrimp"],
      june: ["rooftop crab feast", "waterfront raw bar"],
      july: ["blue crab feast", "boardwalk crab shack"],
      august: ["late summer soft shell crab", "waterfront dinner"],
      september: ["fish and crab special", "harborfront dining"],
      october: ["oyster pairing dinner", "crab dip appetizer"],
      november: ["harbor view dinner", "crab and corn chowder"],
      december: ["holiday prix fixe", "seasonal seafood tower"]
    },
    new_england: {
      january: ["clam chowder dinner", "baked haddock plate"],
      february: ["valentines harbor view dining", "lobster mac and cheese"],
      march: ["maple glazed salmon", "corned beef and cabbage dinner"],
      april: ["fried clams", "spring seafood bake"],
      may: ["lobster roll dinner", "memorial day shore dinner"],
      june: ["lobster bake", "stuffed quahog clams"],
      july: ["clambake on the beach", "lobster dinner"],
      august: ["late summer lobster feast", "clam shack dinner"],
      september: ["apple cider braised pork", "seafood chowder and biscuits"],
      october: ["pumpkin bisque and scallops", "fall tavern dinner"],
      november: ["thanksgiving turkey dinner", "roast root vegetables"],
      december: ["holiday seafood meal", "holiday lobster dinner"]
    },
    great_lakes: {
      january: ["deep dish pizza dinner", "pierogi and sausage plate"],
      february: ["valentines steakhouse", "fireplace wine bar"],
      march: ["corned beef and cabbage pub", "fish fry"],
      april: ["perch fry dinner", "spring lakefront gastropub"],
      may: ["beer garden", "memorial day lakefront grill"],
      june: ["fish fry patio", "waterfront burger bar"],
      july: ["rooftop barbecue platter", "cheese curds and beer"],
      august: ["late summer lakefront grill", "walleye dinner special"],
      september: ["oktoberfest dinner", "beer hall pretzel and stein"],
      october: ["harvest pasta dinner", "comfort food casserole"],
      november: ["thanksgiving turkey dinner", "cozy supper club dining"],
      december: ["holiday prime rib", "holiday dinner out"]
    },
    california: {
      january: ["seafood stew", "winter citrus salad menu"],
      february: ["valentines wine pairing", "romantic coastal seafood"],
      march: ["spring tasting menu", "tri tip dinner"],
      april: ["patio tapas", "small plates dinner"],
      may: ["memorial day seafood grill", "vineyard steak dinner"],
      june: ["summer wine dinner", "oceanfront fish tacos"],
      july: ["beachside fish taco stand", "sushi dinner"],
      august: ["tomato tasting menu", "late summer patio wine dinner"],
      september: ["harvest winemaker dinner", "braised short ribs"],
      october: ["pumpkin gnocchi", "fall coastal chowder"],
      november: ["wine country dinner", "duck dinner"],
      december: ["holiday tasting menu", "seafood cioppino"]
    },
    hawaii: {
      january: ["poke bowl dinner", "garlic shrimp plate"],
      february: ["valentines oceanfront seafood", "sunset poke and wine"],
      march: ["teriyaki plate lunch dinner", "loco moco comfort dinner"],
      april: ["island-style fish tacos", "kalua pork plate"],
      may: ["lei day special menu", "grilled mahi mahi dinner"],
      june: ["sunset beachfront seafood platter", "huli huli chicken dinner"],
      july: ["oceanfront ahi steak", "tropical fruit dessert menu"],
      august: ["late summer poke flight", "waterfront dinner"],
      september: ["shoyu chicken dinner", "local plate lunch evening"],
      october: ["island food and wine menu", "poke and sashimi platter"],
      november: ["holiday turkey dinner", "hawaiian-style buffet dinner"],
      december: ["holiday luau buffet", "holiday prime rib dinner"]
    },
    alaska: {
      january: ["king crab dinner", "salmon chowder and sourdough"],
      february: ["valentines seafood dinner", "sausage entree"],
      march: ["smoked salmon platter", "hearty stew"],
      april: ["halibut dinner", "cod fish and chips"],
      may: ["halibut special", "dockside seafood grill"],
      june: ["salmon barbecue", "waterfront crab boil"],
      july: ["grilled salmon dinner", "seafood combo platter"],
      august: ["fresh salmon menu", "black cod entree"],
      september: ["hearty stew", "fall seafood chowder"],
      october: ["meatloaf dinner", "cozy lodge comfort food"],
      november: ["holiday seafood and game", "crab bisque starter"],
      december: ["holiday crab dinner", "lodge dining"]
    }
  }
