export const COFFEE_BRUNCH_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["cozy coffee shop", "single origin pour over"],
      february: ["valentines brunch", "romantic cafe"],
      march: ["spring cafe patio", "coffee roastery tour"],
      april: ["spring patio cafe", "outdoor espresso bar"],
      may: ["memorial day brunch", "patio latte and pastry"],
      june: ["summer brunch", "cold brew flight"],
      july: ["iced latte", "patio cafe"],
      august: ["late summer brunch bowl", "waterfront coffee seating"],
      september: ["maple latte", "pumpkin spice coffee"],
      october: ["pumpkin spice latte", "fall brunch"],
      november: ["cozy coffee shop", "holiday spice latte preview"],
      december: ["holiday latte", "peppermint mocha seasonal"]
    },
    mountain: {
      january: ["cozy mountain cafe", "hot chocolate apres"],
      february: ["valentines mountain brunch", "romantic fireside cafe"],
      march: ["spring ski town brunch", "cabin style cafe"],
      april: ["mountain view cafe", "hearty breakfast"],
      may: ["memorial day mountain brunch", "outdoor cafe opens"],
      june: ["summer brunch", "mountain view patio coffee"],
      july: ["mountain cafe patio", "cold brew after hike"],
      august: ["late summer trailhead brunch", "outdoor coffee with views"],
      september: ["fall mountain cafe", "pumpkin spice latte"],
      october: ["maple cinnamon latte", "fall brunch"],
      november: ["thanksgiving brunch buffet", "lodge style cafe"],
      december: ["holiday brunch", "cozy lodge cafe"]
    },
    desert_southwest: {
      january: ["sunny patio cafe", "outdoor cortado"],
      february: ["valentines brunch patio", "mimosa brunch"],
      march: ["spring brunch", "patio coffee and chilaquiles"],
      april: ["courtyard cafe", "patio brunch huevos rancheros"],
      may: ["early morning cafe", "sunrise iced latte"],
      june: ["early morning cold brew", "air conditioned espresso bar"],
      july: ["sunrise coffee on patio", "indoor cafe"],
      august: ["early morning brunch tacos", "indoor cafe wi-fi"],
      september: ["patio season returns", "outdoor cafe sunrise"],
      october: ["perfect patio weather", "fall brunch"],
      november: ["comfortable patio coffee", "thanksgiving weekend brunch"],
      december: ["holiday brunch patio", "holiday horchata latte"]
    },
    gulf_coast: {
      january: ["cozy cafe", "beignets cafe"],
      february: ["mardi gras brunch", "king cake latte"],
      march: ["spring cafe patio", "chicory coffee and beignets"],
      april: ["spring patio cafe", "jazz brunch"],
      may: ["memorial day brunch", "patio cafe with live music"],
      june: ["summer brunch", "outdoor cafe by the river"],
      july: ["indoor cafe", "iced chicory coffee"],
      august: ["air conditioned cafe", "cold brew chicory"],
      september: ["fall cafe by the bayou", "comfortable patio beignets"],
      october: ["fall brunch shrimp and grits", "pumpkin beignets"],
      november: ["cozy cafe with pralines", "thanksgiving weekend brunch"],
      december: ["holiday brunch with beignets", "holiday cafe drinks"]
    },
    atlantic_south: {
      january: ["cozy beach town cafe", "winter coastal coffee"],
      february: ["valentines brunch", "marsh view cafe"],
      march: ["spring patio cafe", "porch swing coffee"],
      april: ["beach cafe spring", "patio sweet tea and latte"],
      may: ["memorial day beach brunch", "beach cafe biscuits"],
      june: ["summer brunch", "beachfront acai bowl cafe"],
      july: ["beach coffee morning", "iced sweet cream cold brew"],
      august: ["late summer brunch", "beach cafe beignets"],
      september: ["comfortable patio cafe", "fall brunch"],
      october: ["pumpkin spice on the porch", "fall beach brunch"],
      november: ["cozy beach cafe", "thanksgiving weekend brunch"],
      december: ["holiday beach brunch", "holiday coastal cafe"]
    },
    mid_atlantic: {
      january: ["cozy neighborhood cafe", "winter specialty latte"],
      february: ["valentines brunch", "romantic city cafe"],
      march: ["spring cafe", "cherry blossom brunch"],
      april: ["spring patio cafe", "cherry blossom latte"],
      may: ["memorial day brunch", "patio cafe along the river"],
      june: ["summer brunch", "outdoor cafe"],
      july: ["patio cafe summer", "iced coffee on the waterfront"],
      august: ["late summer brunch", "outdoor cafe"],
      september: ["fall patio cafe", "autumn spice latte"],
      october: ["pumpkin spice latte", "fall brunch in historic district"],
      november: ["cozy cafe with books", "thanksgiving brunch"],
      december: ["holiday brunch", "holiday cafe drinks"]
    },
    new_england: {
      january: ["cozy harbor cafe", "hot chocolate with whipped cream"],
      february: ["valentines brunch", "romantic harborview cafe"],
      march: ["spring cafe", "maple latte"],
      april: ["spring harbor cafe", "maple treat stop"],
      may: ["memorial day brunch", "outdoor harbor cafe"],
      june: ["summer brunch", "harbor cafe patio"],
      july: ["waterfront cafe", "iced coffee by the docks"],
      august: ["late summer brunch", "harbor cafe brunch"],
      september: ["fall harbor cafe", "apple cider donut stop"],
      october: ["pumpkin spice latte", "apple cider brunch"],
      november: ["cozy cafe", "maple hot chocolate"],
      december: ["holiday brunch", "holiday hot chocolate"]
    },
    great_lakes: {
      january: ["cozy lakefront cafe", "winter latte"],
      february: ["valentines brunch downtown", "romantic cafe"],
      march: ["spring cafe", "st patricks brunch and coffee"],
      april: ["spring lakefront cafe", "patio opening weekend"],
      may: ["memorial day brunch", "lakefront patio coffee"],
      june: ["summer brunch", "lakefront cafe"],
      july: ["outdoor lakefront brunch", "iced coffee by the pier"],
      august: ["late summer brunch", "lakefront cafe waffles"],
      september: ["fall lakefront cafe", "maple and caramel latte"],
      october: ["pumpkin spice lakefront", "fall brunch"],
      november: ["cozy cafe", "thanksgiving brunch"],
      december: ["holiday brunch", "holiday lakefront cafe"]
    },
    california: {
      january: ["coastal cafe", "farm fresh brunch"],
      february: ["valentines brunch", "wine country cafe"],
      march: ["spring avocado toast brunch", "patio cafe"],
      april: ["spring cafe with citrus", "farm to table brunch"],
      may: ["memorial day brunch", "outdoor beach cafe"],
      june: ["summer brunch", "beach cafe smoothies"],
      july: ["coastal cafe summer", "nitro cold brew bar"],
      august: ["late summer brunch with berries", "beach cafe acai bowls"],
      september: ["fall cafe", "wine country brunch"],
      october: ["pumpkin spice in wine country", "fall brunch on patio"],
      november: ["thanksgiving weekend brunch", "farm to table cafe"],
      december: ["holiday coastal brunch", "holiday coastal cafe"]
    },
    hawaii: {
      january: ["beach cafe", "kona coffee pour over"],
      february: ["valentines brunch", "ocean view cafe acai bowls"],
      march: ["spring brunch", "beach cafe loco moco"],
      april: ["tropical cafe", "fresh juice bar"],
      may: ["memorial day brunch", "beach cafe pancakes with coconut"],
      june: ["summer brunch", "ocean cafe latte with macadamia milk"],
      july: ["beach cafe morning", "tropical iced coffee"],
      august: ["oceanfront cafe", "kona cold brew"],
      september: ["beach cafe", "island style coffee"],
      october: ["pumpkin spice with coconut", "fall tropical brunch"],
      november: ["thanksgiving brunch island", "ocean cafe malasadas"],
      december: ["holiday brunch beach", "holiday island cafe"]
    },
    alaska: {
      january: ["cozy winter cafe", "hot chocolate after aurora"],
      february: ["valentines brunch", "romantic cabin cafe"],
      march: ["spring brunch", "sled race morning coffee"],
      april: ["spring cafe", "local roaster pour over"],
      may: ["memorial day brunch", "outdoor cafe starts"],
      june: ["midnight sun cafe", "late daylight patio coffee"],
      july: ["outdoor cafe summer", "cold brew in midnight sun"],
      august: ["late summer brunch", "outdoor cafe"],
      september: ["fall cafe", "spiced latte before aurora"],
      october: ["pumpkin spice season", "fall brunch"],
      november: ["cozy cafe", "hot chocolate"],
      december: ["holiday brunch", "winter cafe"]
    }
  }
