export const NATURE_OUTDOORS_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["winter waterfall hike", "rainforest trail walk"],
      february: ["coastal storm lookout", "rainforest boardwalk trail"],
      march: ["spring waterfall hike", "early wildflower trail"],
      april: ["tulip festival", "cherry blossom park"],
      may: ["wildflower ridge trail", "snowmelt waterfall trail"],
      june: ["alpine lake hike", "cedar grove trail"],
      july: ["mountain lake campground", "berry picking trail"],
      august: ["wildflower meadow hike", "alpine ridge hike"],
      september: ["river overlook trail", "early fall forest hike"],
      october: ["fall color hike", "pumpkin patch farm"],
      november: ["coastal viewpoint walk", "storm watching beach"],
      december: ["snowy forest trail", "christmas tree farm"]
    },
    mountain: {
      january: ["ski resort", "winter scenic overlook"],
      february: ["snowy trailhead hike", "hot springs winter soak"],
      march: ["late season skiing", "spring snow hike"],
      april: ["foothills wildflower hike", "snowmelt waterfall trail"],
      may: ["aspen grove spring trail", "mountain pass scenic drive"],
      june: ["high alpine lake hike", "wildflower meadow trail"],
      july: ["mountain reservoir boat rentals", "wildflower trail hike"],
      august: ["high peak summit", "alpine meadow hike"],
      september: ["aspen scenic byway", "mountain pass fall colors"],
      october: ["wildlife viewing area", "late season aspen hike"],
      november: ["early snow hiking trail", "ridge overlook walk"],
      december: ["snowshoe loop trail", "ski village lights"]
    },
    desert_southwest: {
      january: ["saguaro desert hike", "sonoran scenic trail"],
      february: ["sunrise summit trail", "desert butte hike"],
      march: ["desert wildflower bloom", "poppy trail walk"],
      april: ["desert canyon wildflowers", "spring desert ridge hike"],
      may: ["cactus bloom trail", "early morning desert hike"],
      june: ["sunrise desert ridge", "summer solstice overlook"],
      july: ["monsoon desert overlook", "cool cavern tour"],
      august: ["desert after rain trail", "monsoon storm viewpoints"],
      september: ["cooler desert sunrise hike", "canyon trail hike"],
      october: ["red rock canyon trail", "fall desert hike"],
      november: ["desert botanical garden walk", "slot canyon hike"],
      december: ["winter desert sunrise", "desert sunset overlook"]
    },
    gulf_coast: {
      january: ["winter coastal birding", "barrier island beach walk"],
      february: ["bayou tour", "winter bird migration coast"],
      march: ["spring bird migration coast", "swamp boardwalk trail"],
      april: ["spring swamp boat tour", "bird sanctuary walk"],
      may: ["sea turtle nesting beach", "coastal dune wildflowers"],
      june: ["sunrise summer beach", "early morning bayou tour"],
      july: ["coastal wildlife walk", "summer birding refuge"],
      august: ["airboat swamp tour", "bayou boardwalk trail"],
      september: ["shorebird migration", "pleasant evening beach"],
      october: ["fall bird migration", "swamp fall colors"],
      november: ["late fall coastal birding", "migration coast walk"],
      december: ["winter birding refuge", "holiday beach walk"]
    },
    atlantic_south: {
      january: ["winter barrier island walk", "maritime forest trail"],
      february: ["whale watching cruise", "winter coastal nature trail"],
      march: ["spring beach nature walk", "coastal marsh boardwalk"],
      april: ["beach dune wildflowers", "spring maritime forest hike"],
      may: ["sea turtle nesting beach", "memorial day beach sunrise"],
      june: ["turtle nesting walk", "summer solstice beach"],
      july: ["sunrise beach walk", "salt marsh kayak tour"],
      august: ["beach nature preserve", "morning forest trail"],
      september: ["fall coastal bird migration", "pleasant weather beach"],
      october: ["fall barrier island hike", "cool coastal trail"],
      november: ["thanksgiving beach sunrise", "late fall coastal hike"],
      december: ["winter dunes nature walk", "holiday beach stroll"]
    },
    mid_atlantic: {
      january: ["winter bayfront trail", "estuary overlook"],
      february: ["wildlife viewing area", "winter state park shoreline"],
      march: ["spring shorebird migration bay", "early spring marsh trail"],
      april: ["cherry blossom waterfront walk", "spring estuary boardwalk"],
      may: ["memorial day bay trail", "spring coastal rail trail"],
      june: ["summer solstice bayfront", "island nature trail bay"],
      july: ["wild horses beach access", "summer bayfront path"],
      august: ["late summer bay sunset", "coastal wildlife preserve"],
      september: ["fall migration bay overlook", "cool weather bay trail"],
      october: ["fall foliage overlook", "autumn state park loop"],
      november: ["thanksgiving bayfront walk", "late fall coastal colors"],
      december: ["winter coastal boardwalk", "holiday harbor lights"]
    },
    new_england: {
      january: ["winter coastal lighthouse", "snowy harbor walk"],
      february: ["rocky winter coastline", "seaside trail walk"],
      march: ["maple sugar house tour", "early spring coastal walk"],
      april: ["spring lighthouse trail", "maple syrup farm visit"],
      may: ["memorial day coastal walk", "lighthouse seaside trail"],
      june: ["summer solstice beach", "carriage road biking"],
      july: ["carriage road hike", "summer coastal cliff trail"],
      august: ["late summer rocky coast", "lighthouse scenic overlook"],
      september: ["scenic highway foliage drive", "early fall mountain colors"],
      october: ["peak foliage mountain hike", "covered bridge foliage tour"],
      november: ["thanksgiving coastal stroll", "late fall lighthouse visit"],
      december: ["winter harbor village walk", "holiday lighthouse lights"]
    },
    great_lakes: {
      january: ["winter lakeshore walk", "ice formations along lake"],
      february: ["ice caves lakeshore", "winter dune overlook"],
      march: ["early spring lakeshore walk", "spring thaw river trail"],
      april: ["spring dune boardwalk", "riverwalk blossom trail"],
      may: ["memorial day beach park", "spring lakefront bike trail"],
      june: ["summer solstice lakeshore", "bluff lakeshore trail"],
      july: ["dune climb lake overlook", "summer harbor lakefront"],
      august: ["late summer beach day", "great lakes sunset overlook"],
      september: ["fall color lakeshore drive", "autumn riverwalk foliage"],
      october: ["fall dunes overlook", "lakeshore fall color trail"],
      november: ["thanksgiving lakefront walk", "late fall dune trail"],
      december: ["winter lakeshore lights", "holiday riverwalk lights"]
    },
    california: {
      january: ["whale watching overlook", "elephant seal viewing area"],
      february: ["whale watching cruise", "almond blossom scenic drive"],
      march: ["poppy bloom reserve", "wildflower trail"],
      april: ["wildflower overlook", "spring canyon hike"],
      may: ["foothill wildflower trail", "coastal bluff hiking trail"],
      june: ["summer solstice beach walk", "morning fog coastal trail"],
      july: ["coastal morning hike", "redwood grove shaded trail"],
      august: ["cool coastal bluff walk", "redwood canyon trail"],
      september: ["pleasant beach day", "fall canyon hike"],
      october: ["wine country harvest hike", "autumn canyon overlook"],
      november: ["thanksgiving coastal hike", "fall vineyard color walk"],
      december: ["winter whale watching", "holiday coastal harbor walk"]
    },
    hawaii: {
      january: ["whale lookout", "waterfall valley hike"],
      february: ["whale watching cruise", "island nature event"],
      march: ["tropical spring bloom hike", "waterfall scenic drive"],
      april: ["waterfall canyon trail", "tropical garden walk"],
      may: ["memorial day beach park", "tropical flower garden visit"],
      june: ["summer solstice island beach", "tropical garden tour"],
      july: ["reef snorkel spot", "summer beach day"],
      august: ["white sand beach day", "tropical garden peak bloom"],
      september: ["pleasant ridge hike", "tropical forest trail"],
      october: ["beach sunset walk", "comfortable trail hike"],
      november: ["whale season lookout", "tropical arboretum walk"],
      december: ["whale season lookout", "holiday beach lights"]
    },
    alaska: {
      january: ["winter scenic overlook", "hot springs visit"],
      february: ["winter night sky tour", "cozy winter cabin stay"],
      march: ["late winter tour", "sled dog trail"],
      april: ["spring wildlife viewing drive", "glacier boat tour"],
      may: ["midnight sun hiking trail", "spring wilderness day hike"],
      june: ["midnight sun festival park", "summer solstice hike"],
      july: ["salmon viewing platform", "bear viewing river"],
      august: ["salmon run waterfall", "wildlife viewing area"],
      september: ["fall colors national park", "early fall scenic drive"],
      october: ["fall scenic overlook", "autumn trail walk"],
      november: ["winter tour meeting point", "cozy cabin overlook"],
      december: ["holiday winter tour", "winter lodge lights"]
    }
  }
