export const NIGHTLIFE_SOCIAL_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["cozy craft beer pub", "whiskey bar"],
      february: ["valentines cocktail bar", "romantic lounge"],
      march: ["spring beer garden opening", "irish pub with live music"],
      april: ["spring rooftop taproom", "cocktail bar"],
      may: ["memorial day rooftop brewery", "craft beer night"],
      june: ["summer brewery patio", "rooftop bar season"],
      july: ["waterfront beer garden", "rooftop cocktail bar"],
      august: ["late summer rooftop pints", "outdoor cider house"],
      september: ["fall seasonal ale taphouse", "whiskey bar"],
      october: ["oktoberfest beer hall", "fall beer release"],
      november: ["cozy neighborhood lounge", "whiskey bar"],
      december: ["holiday cocktail pop up", "new years eve party"]
    },
    mountain: {
      january: ["apres ski bar", "fireplace lodge lounge"],
      february: ["valentines wine bar", "fireside cocktails"],
      march: ["ski town bar", "closing day patio party"],
      april: ["spring lodge bar", "mountain whiskey lounge"],
      may: ["outdoor beer garden", "patio cider bar"],
      june: ["mountaintop bar", "mountain rooftop cocktails"],
      july: ["brewery beer garden", "live music bar"],
      august: ["riverside bar", "mountain cocktail lounge"],
      september: ["fall lodge lounge", "whiskey bar"],
      october: ["oktoberfest tent", "fall craft beer bar"],
      november: ["fireplace bourbon bar", "ski film night pub"],
      december: ["holiday lodge bar", "new year countdown"]
    },
    desert_southwest: {
      january: ["heated patio margarita bar", "outdoor firepit lounge"],
      february: ["valentines rooftop tequila bar", "romantic lounge"],
      march: ["spring patio bar", "tequila and mezcal bar"],
      april: ["rooftop cocktail bar", "patio paloma night"],
      may: ["sunset patio drinks", "outdoor cantina bar"],
      june: ["indoor speakeasy", "late night tequila lounge"],
      july: ["cool indoor cocktail bar", "evening rooftop breeze"],
      august: ["indoor mezcal lounge", "storm view bar"],
      september: ["patio season returns", "outdoor cantina patio"],
      october: ["perfect patio weather bar", "fall themed bar"],
      november: ["starry night patio bar", "tequila and taco bar"],
      december: ["holiday rooftop bar", "holiday lounge"]
    },
    gulf_coast: {
      january: ["cozy cajun bar", "jazz lounge"],
      february: ["mardi gras balcony bar", "hurricane cocktail bar"],
      march: ["spring patio bar", "irish pub with live band"],
      april: ["jazz fest after show bar", "spring courtyard cocktails"],
      may: ["memorial day riverfront bar", "patio daiquiri bar"],
      june: ["summer rooftop bar", "live blues bar"],
      july: ["outdoor cajun bar", "live music venue"],
      august: ["air conditioned jazz club", "cocktail bar in historic district"],
      september: ["fall patio cocktail bar", "whiskey and rye bar"],
      october: ["halloween themed bar", "costume party bar"],
      november: ["cozy bourbon lounge", "old fashioned whiskey bar"],
      december: ["holiday cocktail bar", "holiday cocktail menu"]
    },
    atlantic_south: {
      january: ["cozy coastal bar", "winter bourbon cocktails"],
      february: ["valentines beach cocktail bar", "romantic rooftop lounge"],
      march: ["spring beach tiki bar", "st patricks pub crawl"],
      april: ["spring pier bar", "ocean view cocktail bar"],
      may: ["memorial day beach bar", "rooftop harbor bar"],
      june: ["summer beach party bar", "beach bar peak season"],
      july: ["outdoor beach bar with live band", "summer tiki lounge"],
      august: ["late summer beach rooftop", "harbor view bar"],
      september: ["fall patio oyster bar", "outdoor cocktails"],
      october: ["fall beach firepit bar", "oktoberfest beer night"],
      november: ["cozy beach whiskey lounge", "bourbon and rye bar"],
      december: ["holiday beach bar lights", "holiday coastal party"]
    },
    mid_atlantic: {
      january: ["cozy historic bar", "downtown speakeasy"],
      february: ["valentines cocktail lounge", "romantic wine bar"],
      march: ["spring city pub night", "irish pub with live music"],
      april: ["spring rooftop opens", "patio cocktail bar"],
      may: ["memorial day rooftop happy hour", "beer garden with string lights"],
      june: ["summer rooftop bar", "rooftop peak season"],
      july: ["rooftop bar", "outdoor beer garden"],
      august: ["late summer rooftop cocktails", "beer garden picnic tables"],
      september: ["fall beer garden", "whiskey bar"],
      october: ["oktoberfest stein night", "fall craft cocktail lounge"],
      november: ["cozy lounge", "bourbon and cigar bar"],
      december: ["holiday party bar", "holiday cocktail pop up"]
    },
    new_england: {
      january: ["cozy harbor tavern", "fireplace whiskey lounge"],
      february: ["valentines harborview lounge", "romantic fireplace bar"],
      march: ["spring neighborhood bar", "irish pub with live music"],
      april: ["spring harbor bar", "waterfront patio bar opens"],
      may: ["memorial day harbor rooftop", "outdoor dock bar"],
      june: ["summer harbor bar", "harbor rooftop cocktails"],
      july: ["waterfront bar", "rooftop summer drinks"],
      august: ["late summer harbor patio", "rooftop gin bar"],
      september: ["fall harbor lounge", "whiskey bar"],
      october: ["halloween costume bar night", "oktoberfest beer hall"],
      november: ["cozy fireplace bar", "bourbon and maple cocktails"],
      december: ["holiday harbor bar", "holiday cocktail lounge"]
    },
    great_lakes: {
      january: ["cozy lakefront bar", "winter craft cocktails"],
      february: ["valentines downtown lounge", "romantic wine and cocktail bar"],
      march: ["spring bar night", "st patricks riverfront pub"],
      april: ["spring lakefront bar", "patio opens for beers"],
      may: ["memorial day lakefront bar", "outdoor beer garden"],
      june: ["summer bar", "lakefront rooftop cocktails"],
      july: ["rooftop bar with skyline view", "lakefront beach bar"],
      august: ["late summer lakefront drinks", "outdoor patio bar"],
      september: ["fall lakefront bar", "oktoberfest beer garden"],
      october: ["oktoberfest stein specials", "fall whiskey lounge"],
      november: ["cozy neighborhood lounge", "whiskey and rye bar"],
      december: ["holiday party bar", "holiday lakefront cocktail bar"]
    },
    california: {
      january: ["coastal wine bar", "beach town cocktail lounge"],
      february: ["valentines wine bar", "romantic coastal lounge"],
      march: ["spring rooftop bar", "beer garden in the sun"],
      april: ["spring patio bar", "wine tasting room night"],
      may: ["memorial day rooftop party", "beach bar sunset drinks"],
      june: ["summer rooftop bar", "oceanfront tiki bar"],
      july: ["beach bar summer night", "rooftop cocktail lounge"],
      august: ["late summer rooftop sunset", "beach bar with live DJ"],
      september: ["fall wine bar", "rooftop wine flights"],
      october: ["wine harvest celebration", "craft cocktail lounge"],
      november: ["cozy coastal lounge", "bourbon and wine bar"],
      december: ["holiday rooftop party", "holiday cocktail bar"]
    },
    hawaii: {
      january: ["beach bar sunset", "tiki bar mai tai night"],
      february: ["valentines beach bar", "romantic oceanfront lounge"],
      march: ["spring beach bar", "tiki lounge with live music"],
      april: ["tropical cocktail lounge", "beachfront rum bar"],
      may: ["memorial day beach bar", "tiki bar with live music"],
      june: ["summer beach party", "beach bar peak season"],
      july: ["tiki lounge summer", "beach bar with live music"],
      august: ["late summer beach bar", "tropical drinks happy hour"],
      september: ["sunset beach bar", "island tiki lounge"],
      october: ["tropical halloween party", "tiki bar costume night"],
      november: ["thanksgiving beach bar", "island cocktail lounge"],
      december: ["holiday beach bar lights", "holiday tropical cocktail bar"]
    },
    alaska: {
      january: ["winter lodge bar", "cozy fireplace lounge"],
      february: ["valentines lodge bar", "winter party bar"],
      march: ["sled race celebration bar", "cozy pub with live music"],
      april: ["spring lodge bar", "local brewery taproom"],
      may: ["outdoor deck bar opens", "midnight sun cocktails"],
      june: ["midnight sun bar", "outdoor riverside lounge"],
      july: ["midnight sun rooftop", "outdoor bar peak season"],
      august: ["late summer harbor bar", "outdoor lounge by the water"],
      september: ["fall lounge", "whiskey bar"],
      october: ["fall bar night", "cocktail lounge"],
      november: ["winter whiskey lounge", "bourbon bar"],
      december: ["holiday bar party", "holiday lounge"]
    }
  }
