export const SPORTS_REC_GEO_SEASON_QUERIES = {
    pacific_northwest: {
      january: ["indoor climbing gym", "ski resort slopes"],
      february: ["snowboarding terrain park", "local ski hill"],
      march: ["spring skiing", "early season mountain biking"],
      april: ["sea kayak tour", "spring trail mountain biking"],
      may: ["sea kayaking tour", "mountain bike flow trails"],
      june: ["paddleboard or kayak rental", "alpine mountain bike trail"],
      july: ["whitewater rafting", "downhill bike park"],
      august: ["late summer sea kayaking", "forest trail running"],
      september: ["fall mountain bike loop", "autumn kayak tours"],
      october: ["fall foliage bike trail", "indoor climbing gym"],
      november: ["early ski season", "bouldering gym"],
      december: ["ski resort opening", "winter sports pass"]
    },
    mountain: {
      january: ["alpine ski resort", "ski slopes"],
      february: ["powder day ski area", "snowboarding terrain park"],
      march: ["spring skiing", "late season ski days"],
      april: ["mountain bike trail opening", "fly fishing river"],
      may: ["singletrack mountain biking", "valley fly fishing"],
      june: ["lift-served bike park", "high alpine mountain biking"],
      july: ["downhill bike park", "summer mountain adventure park"],
      august: ["late summer singletrack", "high elevation trail running"],
      september: ["fall colors mountain biking", "trail running ridge views"],
      october: ["shoulder-season biking", "autumn fly fishing"],
      november: ["ice climbing park", "early season ski laps"],
      december: ["ski resort opening", "snowboard park season"]
    },
    desert_southwest: {
      january: ["winter desert golf", "rock climbing area"],
      february: ["spring training baseball", "desert climbing area"],
      march: ["prime desert mountain biking", "rock climbing season"],
      april: ["morning climbing", "desert preserve singletrack"],
      may: ["sunrise desert golf round", "early morning climbing"],
      june: ["desert lake boating", "indoor climbing gym"],
      july: ["sunrise golf tee time", "water park day"],
      august: ["early morning outdoor sports", "indoor rock climbing gym"],
      september: ["desert mountain biking returns", "pleasant weather climbing"],
      october: ["perfect desert golf weather", "climbing preserve"],
      november: ["fall desert golf", "prime climbing season"],
      december: ["winter desert golf escape", "holiday climbing trip"]
    },
    gulf_coast: {
      january: ["winter coastal golf", "fishing charter"],
      february: ["inshore fishing charter", "bayou kayak tour"],
      march: ["spring coastal golf", "bayou kayak season"],
      april: ["local fishing charter", "guided kayak tour"],
      may: ["memorial day fishing trip", "guided kayak tours"],
      june: ["early morning fishing charter", "sunrise bayou paddle"],
      july: ["sunrise fishing charter", "dawn kayak eco tour"],
      august: ["early morning inshore fishing", "summer kayak tours"],
      september: ["inshore fishing season", "pleasant evening kayaking"],
      october: ["fall fishing peak", "autumn bayou kayak"],
      november: ["thanksgiving fishing trip", "late season kayak tour"],
      december: ["winter fishing charter", "holiday coastal golf"]
    },
    atlantic_south: {
      january: ["winter island golf", "ocean fishing pier"],
      february: ["resort island golf", "winter pier fishing"],
      march: ["spring coastal golf", "early season surfing"],
      april: ["surf break", "beach volleyball pickup"],
      may: ["memorial day beach sports", "early summer surf"],
      june: ["summer surf sessions", "beach volleyball tournament"],
      july: ["peak summer surfing", "beach paddle sports"],
      august: ["late summer surf", "evening beach volleyball"],
      september: ["fall surf swells", "shoulder-season golf"],
      october: ["fall surf season", "cool weather golf"],
      november: ["thanksgiving golf round", "fall inshore fishing"],
      december: ["winter coastal golf", "holiday pier fishing"]
    },
    mid_atlantic: {
      january: ["indoor sports complex", "ice skating rink"],
      february: ["downtown ice rink", "indoor climbing wall"],
      march: ["early spring golf range", "sailing club opening"],
      april: ["bay sailing lessons", "harbor kayak rental opens"],
      may: ["memorial day bay sailing", "harbor kayak tours"],
      june: ["summer sunset sail", "peak season kayak rentals"],
      july: ["bay sailing charter", "kayak harbor paddle"],
      august: ["late summer sunset sail", "guided kayak tour"],
      september: ["fall harbor sailing", "autumn bay kayaking"],
      october: ["crisp weather sailing", "fall foliage kayak"],
      november: ["thanksgiving golf special", "late season sailing"],
      december: ["winter ice skating rink", "holiday indoor sports"]
    },
    new_england: {
      january: ["northeastern ski resort", "outdoor ice skating"],
      february: ["alpine skiing weekend", "community ice rink"],
      march: ["late season spring skiing", "spring sailing prep day"],
      april: ["harbor sailing season opens", "whale watching tour"],
      may: ["memorial day harbor sail", "early season whale watching"],
      june: ["summer sunset sail", "whale watching peak season"],
      july: ["harbor daysail charter", "whale watching excursion"],
      august: ["late summer coastal sailing", "whale watching trip"],
      september: ["fall foliage sailing", "shoulder-season whale tour"],
      october: ["coastal fall sailing", "autumn lighthouse boat tour"],
      november: ["late season harbor sail", "early ski season opening"],
      december: ["holiday ski getaway", "frozen pond ice skating"]
    },
    great_lakes: {
      january: ["ice fishing spot", "lakeside ice skating rink"],
      february: ["ice fishing season", "downtown outdoor rink"],
      march: ["late ice fishing season", "spring sports league signup"],
      april: ["open water fishing opener", "marina boat rental"],
      may: ["memorial day fishing trip", "start of boat rental season"],
      june: ["summer lake fishing", "river boat sightseeing"],
      july: ["lake fishing charter", "pontoon boat rental"],
      august: ["late summer fishing", "harbor boat tours"],
      september: ["fall fishing run", "shoulder-season boat rental"],
      october: ["fall river fishing", "autumn color boat tour"],
      november: ["ice fishing gear prep", "late season shoreline fishing"],
      december: ["holiday ice fishing trip", "lakeside ice skating park"]
    },
    california: {
      january: ["winter surf break", "coastal golf course"],
      february: ["winter swell surfing", "dry-season mountain biking"],
      march: ["spring beach surfing", "trail mountain biking opener"],
      april: ["spring beach pickup games", "singletrack mountain biking"],
      may: ["memorial day surf weekend", "early summer trail riding"],
      june: ["summer surf session", "lakeside bike loop"],
      july: ["beach break surfing", "alpine mountain biking"],
      august: ["late summer surf", "peak season trail riding"],
      september: ["fall surf season", "cooler mountain biking"],
      october: ["surf days", "fall color bike trails"],
      november: ["thanksgiving surf trip", "shoulder-season biking"],
      december: ["winter swell surf", "holiday coastal bike ride"]
    },
    hawaii: {
      january: ["winter north shore surf", "reef snorkeling bay"],
      february: ["big wave surf event", "guided snorkel tour"],
      march: ["spring surf sessions", "snorkeling crater reef"],
      april: ["calm water snorkeling", "beginner surf lessons"],
      may: ["memorial day surf weekend", "snorkeling clear water"],
      june: ["summer surf", "boat snorkel tours"],
      july: ["night snorkel tour", "daytime reef snorkel"],
      august: ["late summer surf", "ideal snorkeling conditions"],
      september: ["shoulder-season surf", "snorkeling shoulder season"],
      october: ["fall surf conditions", "guided snorkel tour"],
      november: ["winter surf season", "snorkel tour outing"],
      december: ["winter surf event", "holiday snorkel tour"]
    },
    alaska: {
      january: ["dog sledding tour", "winter snowshoe tour"],
      february: ["sled race tour", "winter adventure sports"],
      march: ["sled dog checkpoint visit", "spring dog mushing tour"],
      april: ["spring fishing season", "early season wildlife boat"],
      may: ["memorial day river fishing", "kayak season kickoff"],
      june: ["midnight sun river fishing", "fjord sea kayaking"],
      july: ["salmon sport fishing", "peak season sea kayaking"],
      august: ["late salmon run fishing", "glacier kayak tour"],
      september: ["fall fishing", "fall coastal kayaking"],
      october: ["late fall river fishing", "aurora tour"],
      november: ["dog mushing season opens", "early winter tour"],
      december: ["holiday dog sled ride", "winter tour"]
    }
  }
