import {
  Play,
  TrendingUp,
  Sparkles,
  Bookmark,
  Heart,
  MessageCircle,
  Send,
  Music
} from "lucide-react";
import { Button } from "../ui/button";

export function ContentGallery() {
  return (
    <section className="py-20 lg:py-32 bg-background" id="features">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-display-md font-header font-semibold text-foreground mb-4">
            Stunning Content, Instantly
          </h2>
          <p className="text-body-md text-muted-foreground max-w-xl mx-auto">
            Explore examples of high-converting content generated by
            Zencourt&apos;s AI for real estate professionals.
          </p>
        </div>

        <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
          {/* Reel Card 1 */}
          <div className="break-inside-avoid relative rounded-2xl overflow-hidden shadow-md group cursor-pointer">
            <div className="aspect-9/16 bg-linear-to-br from-accent/20 to-secondary relative">
              <div className="absolute inset-0 bg-linear-to-t from-black/60 via-transparent to-transparent opacity-60" />
              <div className="absolute bottom-4 left-4 right-4 text-white">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-6 h-6 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center text-xs border border-white/20">
                    JD
                  </div>
                  <span className="text-xs font-medium">@luxeproperties</span>
                </div>
                <p className="text-sm font-medium leading-snug">
                  Just listed! This view is everything 🌊 #LuxuryRealEstate
                </p>
              </div>
              <div className="absolute top-4 right-4 bg-black/30 backdrop-blur-md p-1.5 rounded-full">
                <Play className="h-4 w-4 text-white" fill="white" />
              </div>
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-white/20 backdrop-blur-md flex items-center justify-center border border-white/30 opacity-0 group-hover:opacity-100 transition-opacity">
                <Play className="h-6 w-6 text-white" fill="white" />
              </div>
            </div>
          </div>

          {/* Instagram Post Card */}
          <div className="break-inside-avoid bg-background rounded-2xl border border-border shadow-md overflow-hidden hover:shadow-xl transition-shadow">
            <div className="p-3 flex items-center justify-between border-b border-border">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center text-xs font-bold text-muted-foreground">
                  AG
                </div>
                <span className="text-sm font-semibold text-foreground">
                  agent_grace
                </span>
              </div>
              <span className="text-muted-foreground text-sm">•••</span>
            </div>
            <div className="aspect-square bg-linear-to-br from-secondary to-accent/20 relative" />
            <div className="p-4">
              <div className="flex gap-4 mb-3">
                <Heart className="h-5 w-5 text-foreground" />
                <MessageCircle className="h-5 w-5 text-foreground" />
                <Send className="h-5 w-5 text-foreground" />
              </div>
              <p className="text-sm text-foreground">
                <span className="font-semibold">agent_grace</span> Modern
                minimalist design in the heart of downtown. Open house this
                Sunday! 🏡
              </p>
              <p className="text-xs text-muted-foreground mt-2 uppercase">
                2 hours ago
              </p>
            </div>
          </div>

          {/* Stats Card */}
          <div className="break-inside-avoid bg-primary text-primary-foreground p-6 rounded-2xl shadow-lg flex flex-col justify-center min-h-[160px] relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2" />
            <div className="flex items-center gap-2 mb-2 opacity-70 relative z-10">
              <TrendingUp className="h-4 w-4" />
              <span className="text-xs uppercase tracking-wider font-semibold">
                Viral Reach
              </span>
            </div>
            <div className="text-4xl font-header font-bold mb-2 relative z-10">
              24.5k
            </div>
            <div className="text-xs opacity-70 relative z-10">
              People reached in the last 30 days
            </div>
          </div>

          {/* Story View Card */}
          <div className="break-inside-avoid relative rounded-2xl overflow-hidden shadow-lg group hover:ring-4 ring-accent/30 transition-all">
            <div className="aspect-9/15 bg-linear-to-br from-accent/30 to-secondary relative">
              <div className="absolute top-4 left-0 right-0 px-3 flex gap-1">
                <div className="h-0.5 flex-1 bg-white rounded-full" />
                <div className="h-0.5 flex-1 bg-white/40 rounded-full" />
              </div>
              <div className="absolute top-8 left-4 flex items-center gap-2">
                <div className="w-8 h-8 rounded-full border-2 border-accent bg-secondary overflow-hidden" />
                <span className="text-white text-sm font-medium shadow-black drop-shadow-md">
                  Zencourt
                </span>
                <span className="text-white/70 text-xs">2h</span>
              </div>
              <div className="absolute bottom-12 inset-x-8 bg-white/90 backdrop-blur-md p-4 rounded-xl text-center shadow-lg transform translate-y-2 opacity-90 group-hover:translate-y-0 group-hover:opacity-100 transition-all">
                <p className="text-xs font-bold text-foreground uppercase tracking-wide mb-1">
                  Open House
                </p>
                <p className="text-sm text-muted-foreground font-header">
                  Sunday, 2pm - 4pm
                </p>
                <button className="mt-3 w-full py-1.5 bg-primary text-primary-foreground text-xs rounded-lg">
                  RSVP Now
                </button>
              </div>
            </div>
          </div>

          {/* Property Listing Card */}
          <div className="break-inside-avoid bg-background rounded-2xl border border-border shadow-md overflow-hidden">
            <div className="relative">
              <div className="w-full aspect-4/3 bg-linear-to-br from-secondary to-accent/20" />
              <div className="absolute top-3 right-3 bg-black/50 backdrop-blur px-2 py-1 rounded text-white text-xs font-medium">
                1/5
              </div>
            </div>
            <div className="p-4 bg-secondary/50 border-t border-border">
              <div className="flex justify-between items-start">
                <div>
                  <h4 className="font-header font-semibold text-foreground">
                    Modern Loft
                  </h4>
                  <p className="text-xs text-muted-foreground">
                    $1,250,000 • 2 Bed • 2 Bath
                  </p>
                </div>
                <Bookmark className="h-5 w-5 text-muted-foreground cursor-pointer hover:text-accent transition-colors" />
              </div>
            </div>
          </div>

          {/* Testimonial Quote Card */}
          <div className="break-inside-avoid bg-accent/20 p-8 rounded-2xl border border-accent/20 flex flex-col items-center justify-center text-center aspect-square md:aspect-auto">
            <Sparkles className="h-8 w-8 text-foreground mb-3" />
            <p className="font-header text-foreground font-medium text-lg italic leading-relaxed">
              &quot;Sold in record time thanks to these automated reels!&quot;
            </p>
            <p className="text-xs font-bold text-muted-foreground mt-4 uppercase tracking-widest">
              — Sarah J.
            </p>
          </div>

          {/* TikTok Style Reel */}
          <div className="break-inside-avoid relative rounded-2xl overflow-hidden shadow-md group cursor-pointer">
            <div className="aspect-9/16 bg-linear-to-br from-secondary to-accent/10 relative">
              <div className="absolute inset-0 bg-linear-to-b from-transparent via-transparent to-black/80" />
              <div className="absolute bottom-0 inset-x-0 p-5 text-white">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-8 h-8 rounded-full bg-white/20 border border-white/30 backdrop-blur-sm flex items-center justify-center text-xs">
                    TM
                  </div>
                  <div className="text-sm font-semibold">@tim_realtor</div>
                </div>
                <p className="text-sm opacity-90 mb-4 line-clamp-2">
                  5 tips for first time homebuyers you need to know before...
                </p>
                <div className="flex items-center gap-2 text-xs opacity-70">
                  <Music className="h-4 w-4" />
                  <span>Trending Audio • 12k uses</span>
                </div>
              </div>
            </div>
          </div>

          {/* Scheduled Post Card */}
          <div className="break-inside-avoid bg-primary text-primary-foreground rounded-2xl shadow-lg relative group overflow-hidden cursor-pointer aspect-square flex flex-col items-center justify-center text-center p-6">
            <div className="absolute inset-0 bg-linear-to-br from-accent/10 to-transparent opacity-40" />
            <div className="relative z-10">
              <span className="inline-block px-3 py-1 bg-white/20 backdrop-blur rounded-full text-[10px] font-bold uppercase mb-3">
                Scheduled
              </span>
              <h3 className="font-header text-2xl font-bold mb-1">
                New Listing
              </h3>
              <p className="text-primary-foreground/70 text-sm">
                Posting tomorrow at 9AM
              </p>
            </div>
            <div className="absolute bottom-0 left-0 h-1 bg-accent w-full transform scale-x-0 group-hover:scale-x-100 transition-transform origin-left duration-500" />
          </div>
        </div>

        <div className="mt-16 text-center">
          <Button variant="outline" size="lg">
            Explore All Content
          </Button>
        </div>
      </div>
    </section>
  );
}
