export const IMAGE_OVERLAY_BASE_FONT_SIZE_PX = 38;
export const IMAGE_OVERLAY_HORIZONTAL_PADDING_PX = 40;
export const IMAGE_OVERLAY_BOX_PADDING_VERTICAL_PX = 10;
export const IMAGE_OVERLAY_BOX_PADDING_HORIZONTAL_PX = 16;
