export enum VideoProcessingErrorType {
  STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED",
  STORAGE_DOWNLOAD_FAILED = "STORAGE_DOWNLOAD_FAILED",
  STORAGE_DELETE_FAILED = "STORAGE_DELETE_FAILED",
  STORAGE_ACCESS_DENIED = "STORAGE_ACCESS_DENIED",
  STORAGE_NOT_FOUND = "STORAGE_NOT_FOUND",
  FFMPEG_NOT_FOUND = "FFMPEG_NOT_FOUND",
  FFMPEG_PROCESS_FAILED = "FFMPEG_PROCESS_FAILED",
  FFMPEG_TIMEOUT = "FFMPEG_TIMEOUT",
  FFMPEG_INVALID_INPUT = "FFMPEG_INVALID_INPUT",
  FAL_SUBMISSION_FAILED = "FAL_SUBMISSION_FAILED",
  FAL_GENERATION_FAILED = "FAL_GENERATION_FAILED",
  JOB_TIMEOUT = "JOB_TIMEOUT",
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  WEBHOOK_DELIVERY_FAILED = "WEBHOOK_DELIVERY_FAILED",
  WEBHOOK_INVALID_SIGNATURE = "WEBHOOK_INVALID_SIGNATURE",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_API_KEY = "INVALID_API_KEY",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}

export type ApiErrorCode =
  | "INVALID_REQUEST"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "VIDEO_SERVER_ERROR"
  | "VIDEO_STATUS_ERROR"
  | "WEBHOOK_VERIFICATION_ERROR"
  | "INTERNAL_ERROR"
  | "DATABASE_ERROR"
  | VideoProcessingErrorType;

export enum StatusCode {
  OK = 200,
  ACCEPTED = 202,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502
}

export interface ApiErrorBody {
  success: false;
  code: ApiErrorCode;
  error: string;
}
