import * as React from "react";
import type { ContentItem } from "@web/src/components/dashboard/components/ContentGrid";
import {
  buildPreviewTimelinePlan,
  type PreviewTimelinePlan
} from "@web/src/components/listings/create/domain/previewTimeline";
import {
  type PreviewClipCandidate,
  filterFeatureClips
} from "@web/src/components/listings/create/domain/listingCreateUtils";
import type { ListingContentSubcategory } from "@shared/types/models";
import { buildReelSourceKey } from "@web/src/components/listings/create/shared/reels";

const MIN_CLIP_DURATION_SECONDS = 0.5;

function buildAutoGeneratedPreviewSeed(params: {
  activeSubcategory: ListingContentSubcategory;
  captionItem: ContentItem;
}) {
  const { activeSubcategory, captionItem } = params;
  const cachedCaptionItem = captionItem as ContentItem & {
    cacheKeyTimestamp?: number;
    cacheKeyId?: number;
  };

  if (
    typeof cachedCaptionItem.cacheKeyTimestamp === "number" &&
    typeof cachedCaptionItem.cacheKeyId === "number"
  ) {
    return `${activeSubcategory}-${cachedCaptionItem.cacheKeyTimestamp}-${cachedCaptionItem.cacheKeyId}`;
  }

  return `${activeSubcategory}-${captionItem.id}`;
}

function applyOrderedClipIds(
  plan: PreviewTimelinePlan,
  orderedClipIds: string[] | null | undefined
): PreviewTimelinePlan {
  if (!orderedClipIds?.length) {
    return plan;
  }

  const segmentByClipId = new Map(
    plan.segments.map((segment) => [segment.clipId, segment])
  );
  const orderedSegments = orderedClipIds
    .map((clipId) => segmentByClipId.get(clipId))
    .filter(
      (segment): segment is PreviewTimelinePlan["segments"][number] =>
        Boolean(segment)
    );
  const remainingSegments = plan.segments.filter(
    (segment) => !orderedClipIds.includes(segment.clipId)
  );

  if (orderedSegments.length === 0) {
    return plan;
  }

  return {
    ...plan,
    segments: [...orderedSegments, ...remainingSegments]
  };
}

function applyClipDurationOverrides(
  plan: PreviewTimelinePlan,
  clipDurationOverrides: Record<string, number> | null | undefined
): PreviewTimelinePlan {
  if (!clipDurationOverrides) {
    return plan;
  }

  const segments = plan.segments.map((segment) => {
    const override = clipDurationOverrides[segment.clipId];
    if (!Number.isFinite(override)) {
      return segment;
    }

    return {
      ...segment,
      durationSeconds: Number(
        Math.min(
          segment.maxDurationSeconds,
          Math.max(MIN_CLIP_DURATION_SECONDS, override)
        ).toFixed(2)
      )
    };
  });

  return {
    ...plan,
    segments,
    totalDurationSeconds: Number(
      segments
        .reduce((sum, segment) => sum + segment.durationSeconds, 0)
        .toFixed(2)
    )
  };
}

export function useListingCreatePreviewPlans(params: {
  listingId: string;
  activeMediaTab: "videos" | "images";
  activeSubcategory: ListingContentSubcategory;
  activeMediaItems: ContentItem[];
  videoItems: ContentItem[];
}) {
  const { listingId, activeMediaTab, activeSubcategory, activeMediaItems, videoItems } = params;

  return React.useMemo(() => {
    return buildListingCreatePreviewPlans({
      listingId,
      activeMediaTab,
      activeSubcategory,
      activeMediaItems,
      videoItems
    });
  }, [activeMediaItems, activeMediaTab, activeSubcategory, listingId, videoItems]);
}

export function buildListingCreatePreviewPlans(params: {
  listingId: string;
  activeMediaTab: "videos" | "images";
  activeSubcategory: ListingContentSubcategory;
  activeMediaItems: ContentItem[];
  videoItems: ContentItem[];
}): PreviewTimelinePlan[] {
  const {
    listingId,
    activeMediaTab,
    activeSubcategory,
    activeMediaItems,
    videoItems
  } = params;

  if (activeMediaTab !== "videos") {
    return [];
  }

  const clipCandidates: PreviewClipCandidate[] = videoItems
    .filter((item) => item.reelClipSource !== "user_media")
    .filter((item) => Boolean(item.videoUrl))
    .map((item) => ({
      id: item.id,
      category: item.category ?? null,
      durationSeconds: item.durationSeconds ?? null,
      isPriorityCategory: item.isPriorityCategory ?? false,
      searchableText: `${item.category ?? ""} ${item.alt ?? ""}`
        .toLowerCase()
        .replace(/[^\w\s]/g, " ")
    }));
  const clipById = new Map(
    videoItems
      .filter((item) => Boolean(item.videoUrl))
      .map((item) => [item.id, item] as const)
  );
  if (activeMediaItems.length === 0) {
    return [];
  }

  return activeMediaItems.map((captionItem): PreviewTimelinePlan => {
    if (captionItem.reelSequence?.length) {
      const segments = captionItem.reelSequence
        .map((sequenceItem) => {
          const clipId = buildReelSourceKey(
            sequenceItem.sourceType,
            sequenceItem.sourceId
          );
          const sourceItem = clipById.get(clipId);
          if (!sourceItem?.videoUrl) {
            return null;
          }

          const maxDurationSeconds = Math.max(
            MIN_CLIP_DURATION_SECONDS,
            sourceItem.durationSeconds ?? sequenceItem.durationSeconds
          );

          return {
            clipId,
            category: sourceItem.category ?? sourceItem.roomName ?? null,
            durationSeconds: Number(
              Math.min(
                maxDurationSeconds,
                Math.max(MIN_CLIP_DURATION_SECONDS, sequenceItem.durationSeconds)
              ).toFixed(2)
            ),
            maxDurationSeconds,
            sourceType: sequenceItem.sourceType,
            sourceId: sequenceItem.sourceId
          };
        })
        .filter(
          (
            segment
          ): segment is NonNullable<typeof segment> => Boolean(segment)
        );

      return {
        id: `saved-plan-${captionItem.id}`,
        segments,
        totalDurationSeconds: Number(
          segments
            .reduce((sum, segment) => sum + segment.durationSeconds, 0)
            .toFixed(2)
        )
      };
    }

    if (clipCandidates.length === 0) {
      return {
        id: `plan-${activeSubcategory}-${captionItem.id}`,
        segments: [],
        totalDurationSeconds: 0
      };
    }

    const scopedClips =
      activeSubcategory === "property_features"
        ? filterFeatureClips(clipCandidates, captionItem)
        : clipCandidates;
    const plan = buildPreviewTimelinePlan({
      clips: scopedClips,
      listingId,
      seedKey: buildAutoGeneratedPreviewSeed({
        activeSubcategory,
        captionItem
      })
    });

    return applyClipDurationOverrides(
      applyOrderedClipIds(plan, captionItem.orderedClipIds),
      captionItem.clipDurationOverrides
    );
  });
}
